// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/accident.proto

package accident

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Accident struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DateTime         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Location         string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Circonstances    string                 `protobuf:"bytes,4,opt,name=circonstances,proto3" json:"circonstances,omitempty"`
	VehicleAId       int64                  `protobuf:"varint,5,opt,name=vehicle_a_id,json=vehicleAId,proto3" json:"vehicle_a_id,omitempty"`
	DriverAId        int64                  `protobuf:"varint,6,opt,name=driver_a_id,json=driverAId,proto3" json:"driver_a_id,omitempty"`
	PointDeChocA     string                 `protobuf:"bytes,7,opt,name=point_de_choc_a,json=pointDeChocA,proto3" json:"point_de_choc_a,omitempty"`
	DegatsApparentsA string                 `protobuf:"bytes,8,opt,name=degats_apparents_a,json=degatsApparentsA,proto3" json:"degats_apparents_a,omitempty"`
	ObservationsA    string                 `protobuf:"bytes,9,opt,name=observations_a,json=observationsA,proto3" json:"observations_a,omitempty"`
	PvPoliceA        string                 `protobuf:"bytes,10,opt,name=pv_police_a,json=pvPoliceA,proto3" json:"pv_police_a,omitempty"`
	PvGendarmerieA   string                 `protobuf:"bytes,11,opt,name=pv_gendarmerie_a,json=pvGendarmerieA,proto3" json:"pv_gendarmerie_a,omitempty"`
	VehicleBId       int64                  `protobuf:"varint,12,opt,name=vehicle_b_id,json=vehicleBId,proto3" json:"vehicle_b_id,omitempty"`
	DriverBId        int64                  `protobuf:"varint,13,opt,name=driver_b_id,json=driverBId,proto3" json:"driver_b_id,omitempty"`
	PointDeChocB     string                 `protobuf:"bytes,14,opt,name=point_de_choc_b,json=pointDeChocB,proto3" json:"point_de_choc_b,omitempty"`
	DegatsApparentsB string                 `protobuf:"bytes,15,opt,name=degats_apparents_b,json=degatsApparentsB,proto3" json:"degats_apparents_b,omitempty"`
	ObservationsB    string                 `protobuf:"bytes,16,opt,name=observations_b,json=observationsB,proto3" json:"observations_b,omitempty"`
	PvPoliceB        string                 `protobuf:"bytes,17,opt,name=pv_police_b,json=pvPoliceB,proto3" json:"pv_police_b,omitempty"`
	PvGendarmerieB   string                 `protobuf:"bytes,18,opt,name=pv_gendarmerie_b,json=pvGendarmerieB,proto3" json:"pv_gendarmerie_b,omitempty"`
	Status           string                 `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Accident) Reset() {
	*x = Accident{}
	mi := &file_proto_accident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accident) ProtoMessage() {}

func (x *Accident) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accident.ProtoReflect.Descriptor instead.
func (*Accident) Descriptor() ([]byte, []int) {
	return file_proto_accident_proto_rawDescGZIP(), []int{0}
}

func (x *Accident) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Accident) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *Accident) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Accident) GetCirconstances() string {
	if x != nil {
		return x.Circonstances
	}
	return ""
}

func (x *Accident) GetVehicleAId() int64 {
	if x != nil {
		return x.VehicleAId
	}
	return 0
}

func (x *Accident) GetDriverAId() int64 {
	if x != nil {
		return x.DriverAId
	}
	return 0
}

func (x *Accident) GetPointDeChocA() string {
	if x != nil {
		return x.PointDeChocA
	}
	return ""
}

func (x *Accident) GetDegatsApparentsA() string {
	if x != nil {
		return x.DegatsApparentsA
	}
	return ""
}

func (x *Accident) GetObservationsA() string {
	if x != nil {
		return x.ObservationsA
	}
	return ""
}

func (x *Accident) GetPvPoliceA() string {
	if x != nil {
		return x.PvPoliceA
	}
	return ""
}

func (x *Accident) GetPvGendarmerieA() string {
	if x != nil {
		return x.PvGendarmerieA
	}
	return ""
}

func (x *Accident) GetVehicleBId() int64 {
	if x != nil {
		return x.VehicleBId
	}
	return 0
}

func (x *Accident) GetDriverBId() int64 {
	if x != nil {
		return x.DriverBId
	}
	return 0
}

func (x *Accident) GetPointDeChocB() string {
	if x != nil {
		return x.PointDeChocB
	}
	return ""
}

func (x *Accident) GetDegatsApparentsB() string {
	if x != nil {
		return x.DegatsApparentsB
	}
	return ""
}

func (x *Accident) GetObservationsB() string {
	if x != nil {
		return x.ObservationsB
	}
	return ""
}

func (x *Accident) GetPvPoliceB() string {
	if x != nil {
		return x.PvPoliceB
	}
	return ""
}

func (x *Accident) GetPvGendarmerieB() string {
	if x != nil {
		return x.PvGendarmerieB
	}
	return ""
}

func (x *Accident) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateAccidentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DateTime         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Location         string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Circonstances    string                 `protobuf:"bytes,3,opt,name=circonstances,proto3" json:"circonstances,omitempty"`
	VehicleAId       int64                  `protobuf:"varint,4,opt,name=vehicle_a_id,json=vehicleAId,proto3" json:"vehicle_a_id,omitempty"`
	DriverAId        int64                  `protobuf:"varint,5,opt,name=driver_a_id,json=driverAId,proto3" json:"driver_a_id,omitempty"`
	PointDeChocA     string                 `protobuf:"bytes,6,opt,name=point_de_choc_a,json=pointDeChocA,proto3" json:"point_de_choc_a,omitempty"`
	DegatsApparentsA string                 `protobuf:"bytes,7,opt,name=degats_apparents_a,json=degatsApparentsA,proto3" json:"degats_apparents_a,omitempty"`
	ObservationsA    string                 `protobuf:"bytes,8,opt,name=observations_a,json=observationsA,proto3" json:"observations_a,omitempty"`
	PvPoliceA        string                 `protobuf:"bytes,9,opt,name=pv_police_a,json=pvPoliceA,proto3" json:"pv_police_a,omitempty"`
	PvGendarmerieA   string                 `protobuf:"bytes,10,opt,name=pv_gendarmerie_a,json=pvGendarmerieA,proto3" json:"pv_gendarmerie_a,omitempty"`
	VehicleBId       int64                  `protobuf:"varint,11,opt,name=vehicle_b_id,json=vehicleBId,proto3" json:"vehicle_b_id,omitempty"`
	DriverBId        int64                  `protobuf:"varint,12,opt,name=driver_b_id,json=driverBId,proto3" json:"driver_b_id,omitempty"`
	PointDeChocB     string                 `protobuf:"bytes,13,opt,name=point_de_choc_b,json=pointDeChocB,proto3" json:"point_de_choc_b,omitempty"`
	DegatsApparentsB string                 `protobuf:"bytes,14,opt,name=degats_apparents_b,json=degatsApparentsB,proto3" json:"degats_apparents_b,omitempty"`
	ObservationsB    string                 `protobuf:"bytes,15,opt,name=observations_b,json=observationsB,proto3" json:"observations_b,omitempty"`
	PvPoliceB        string                 `protobuf:"bytes,16,opt,name=pv_police_b,json=pvPoliceB,proto3" json:"pv_police_b,omitempty"`
	PvGendarmerieB   string                 `protobuf:"bytes,17,opt,name=pv_gendarmerie_b,json=pvGendarmerieB,proto3" json:"pv_gendarmerie_b,omitempty"`
	Status           string                 `protobuf:"bytes,18,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateAccidentRequest) Reset() {
	*x = CreateAccidentRequest{}
	mi := &file_proto_accident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccidentRequest) ProtoMessage() {}

func (x *CreateAccidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccidentRequest.ProtoReflect.Descriptor instead.
func (*CreateAccidentRequest) Descriptor() ([]byte, []int) {
	return file_proto_accident_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccidentRequest) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *CreateAccidentRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateAccidentRequest) GetCirconstances() string {
	if x != nil {
		return x.Circonstances
	}
	return ""
}

func (x *CreateAccidentRequest) GetVehicleAId() int64 {
	if x != nil {
		return x.VehicleAId
	}
	return 0
}

func (x *CreateAccidentRequest) GetDriverAId() int64 {
	if x != nil {
		return x.DriverAId
	}
	return 0
}

func (x *CreateAccidentRequest) GetPointDeChocA() string {
	if x != nil {
		return x.PointDeChocA
	}
	return ""
}

func (x *CreateAccidentRequest) GetDegatsApparentsA() string {
	if x != nil {
		return x.DegatsApparentsA
	}
	return ""
}

func (x *CreateAccidentRequest) GetObservationsA() string {
	if x != nil {
		return x.ObservationsA
	}
	return ""
}

func (x *CreateAccidentRequest) GetPvPoliceA() string {
	if x != nil {
		return x.PvPoliceA
	}
	return ""
}

func (x *CreateAccidentRequest) GetPvGendarmerieA() string {
	if x != nil {
		return x.PvGendarmerieA
	}
	return ""
}

func (x *CreateAccidentRequest) GetVehicleBId() int64 {
	if x != nil {
		return x.VehicleBId
	}
	return 0
}

func (x *CreateAccidentRequest) GetDriverBId() int64 {
	if x != nil {
		return x.DriverBId
	}
	return 0
}

func (x *CreateAccidentRequest) GetPointDeChocB() string {
	if x != nil {
		return x.PointDeChocB
	}
	return ""
}

func (x *CreateAccidentRequest) GetDegatsApparentsB() string {
	if x != nil {
		return x.DegatsApparentsB
	}
	return ""
}

func (x *CreateAccidentRequest) GetObservationsB() string {
	if x != nil {
		return x.ObservationsB
	}
	return ""
}

func (x *CreateAccidentRequest) GetPvPoliceB() string {
	if x != nil {
		return x.PvPoliceB
	}
	return ""
}

func (x *CreateAccidentRequest) GetPvGendarmerieB() string {
	if x != nil {
		return x.PvGendarmerieB
	}
	return ""
}

func (x *CreateAccidentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateAccidentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DateTime         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Location         string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Circonstances    string                 `protobuf:"bytes,4,opt,name=circonstances,proto3" json:"circonstances,omitempty"`
	VehicleAId       int64                  `protobuf:"varint,5,opt,name=vehicle_a_id,json=vehicleAId,proto3" json:"vehicle_a_id,omitempty"`
	DriverAId        int64                  `protobuf:"varint,6,opt,name=driver_a_id,json=driverAId,proto3" json:"driver_a_id,omitempty"`
	PointDeChocA     string                 `protobuf:"bytes,7,opt,name=point_de_choc_a,json=pointDeChocA,proto3" json:"point_de_choc_a,omitempty"`
	DegatsApparentsA string                 `protobuf:"bytes,8,opt,name=degats_apparents_a,json=degatsApparentsA,proto3" json:"degats_apparents_a,omitempty"`
	ObservationsA    string                 `protobuf:"bytes,9,opt,name=observations_a,json=observationsA,proto3" json:"observations_a,omitempty"`
	PvPoliceA        string                 `protobuf:"bytes,10,opt,name=pv_police_a,json=pvPoliceA,proto3" json:"pv_police_a,omitempty"`
	PvGendarmerieA   string                 `protobuf:"bytes,11,opt,name=pv_gendarmerie_a,json=pvGendarmerieA,proto3" json:"pv_gendarmerie_a,omitempty"`
	VehicleBId       int64                  `protobuf:"varint,12,opt,name=vehicle_b_id,json=vehicleBId,proto3" json:"vehicle_b_id,omitempty"`
	DriverBId        int64                  `protobuf:"varint,13,opt,name=driver_b_id,json=driverBId,proto3" json:"driver_b_id,omitempty"`
	PointDeChocB     string                 `protobuf:"bytes,14,opt,name=point_de_choc_b,json=pointDeChocB,proto3" json:"point_de_choc_b,omitempty"`
	DegatsApparentsB string                 `protobuf:"bytes,15,opt,name=degats_apparents_b,json=degatsApparentsB,proto3" json:"degats_apparents_b,omitempty"`
	ObservationsB    string                 `protobuf:"bytes,16,opt,name=observations_b,json=observationsB,proto3" json:"observations_b,omitempty"`
	PvPoliceB        string                 `protobuf:"bytes,17,opt,name=pv_police_b,json=pvPoliceB,proto3" json:"pv_police_b,omitempty"`
	PvGendarmerieB   string                 `protobuf:"bytes,18,opt,name=pv_gendarmerie_b,json=pvGendarmerieB,proto3" json:"pv_gendarmerie_b,omitempty"`
	Status           string                 `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateAccidentResponse) Reset() {
	*x = CreateAccidentResponse{}
	mi := &file_proto_accident_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccidentResponse) ProtoMessage() {}

func (x *CreateAccidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accident_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccidentResponse.ProtoReflect.Descriptor instead.
func (*CreateAccidentResponse) Descriptor() ([]byte, []int) {
	return file_proto_accident_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccidentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateAccidentResponse) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *CreateAccidentResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateAccidentResponse) GetCirconstances() string {
	if x != nil {
		return x.Circonstances
	}
	return ""
}

func (x *CreateAccidentResponse) GetVehicleAId() int64 {
	if x != nil {
		return x.VehicleAId
	}
	return 0
}

func (x *CreateAccidentResponse) GetDriverAId() int64 {
	if x != nil {
		return x.DriverAId
	}
	return 0
}

func (x *CreateAccidentResponse) GetPointDeChocA() string {
	if x != nil {
		return x.PointDeChocA
	}
	return ""
}

func (x *CreateAccidentResponse) GetDegatsApparentsA() string {
	if x != nil {
		return x.DegatsApparentsA
	}
	return ""
}

func (x *CreateAccidentResponse) GetObservationsA() string {
	if x != nil {
		return x.ObservationsA
	}
	return ""
}

func (x *CreateAccidentResponse) GetPvPoliceA() string {
	if x != nil {
		return x.PvPoliceA
	}
	return ""
}

func (x *CreateAccidentResponse) GetPvGendarmerieA() string {
	if x != nil {
		return x.PvGendarmerieA
	}
	return ""
}

func (x *CreateAccidentResponse) GetVehicleBId() int64 {
	if x != nil {
		return x.VehicleBId
	}
	return 0
}

func (x *CreateAccidentResponse) GetDriverBId() int64 {
	if x != nil {
		return x.DriverBId
	}
	return 0
}

func (x *CreateAccidentResponse) GetPointDeChocB() string {
	if x != nil {
		return x.PointDeChocB
	}
	return ""
}

func (x *CreateAccidentResponse) GetDegatsApparentsB() string {
	if x != nil {
		return x.DegatsApparentsB
	}
	return ""
}

func (x *CreateAccidentResponse) GetObservationsB() string {
	if x != nil {
		return x.ObservationsB
	}
	return ""
}

func (x *CreateAccidentResponse) GetPvPoliceB() string {
	if x != nil {
		return x.PvPoliceB
	}
	return ""
}

func (x *CreateAccidentResponse) GetPvGendarmerieB() string {
	if x != nil {
		return x.PvGendarmerieB
	}
	return ""
}

func (x *CreateAccidentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAccidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccidentRequest) Reset() {
	*x = GetAccidentRequest{}
	mi := &file_proto_accident_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccidentRequest) ProtoMessage() {}

func (x *GetAccidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accident_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccidentRequest.ProtoReflect.Descriptor instead.
func (*GetAccidentRequest) Descriptor() ([]byte, []int) {
	return file_proto_accident_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccidentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAccidentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DateTime         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Location         string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Circonstances    string                 `protobuf:"bytes,4,opt,name=circonstances,proto3" json:"circonstances,omitempty"`
	VehicleAId       int64                  `protobuf:"varint,5,opt,name=vehicle_a_id,json=vehicleAId,proto3" json:"vehicle_a_id,omitempty"`
	DriverAId        int64                  `protobuf:"varint,6,opt,name=driver_a_id,json=driverAId,proto3" json:"driver_a_id,omitempty"`
	PointDeChocA     string                 `protobuf:"bytes,7,opt,name=point_de_choc_a,json=pointDeChocA,proto3" json:"point_de_choc_a,omitempty"`
	DegatsApparentsA string                 `protobuf:"bytes,8,opt,name=degats_apparents_a,json=degatsApparentsA,proto3" json:"degats_apparents_a,omitempty"`
	ObservationsA    string                 `protobuf:"bytes,9,opt,name=observations_a,json=observationsA,proto3" json:"observations_a,omitempty"`
	PvPoliceA        string                 `protobuf:"bytes,10,opt,name=pv_police_a,json=pvPoliceA,proto3" json:"pv_police_a,omitempty"`
	PvGendarmerieA   string                 `protobuf:"bytes,11,opt,name=pv_gendarmerie_a,json=pvGendarmerieA,proto3" json:"pv_gendarmerie_a,omitempty"`
	VehicleBId       int64                  `protobuf:"varint,12,opt,name=vehicle_b_id,json=vehicleBId,proto3" json:"vehicle_b_id,omitempty"`
	DriverBId        int64                  `protobuf:"varint,13,opt,name=driver_b_id,json=driverBId,proto3" json:"driver_b_id,omitempty"`
	PointDeChocB     string                 `protobuf:"bytes,14,opt,name=point_de_choc_b,json=pointDeChocB,proto3" json:"point_de_choc_b,omitempty"`
	DegatsApparentsB string                 `protobuf:"bytes,15,opt,name=degats_apparents_b,json=degatsApparentsB,proto3" json:"degats_apparents_b,omitempty"`
	ObservationsB    string                 `protobuf:"bytes,16,opt,name=observations_b,json=observationsB,proto3" json:"observations_b,omitempty"`
	PvPoliceB        string                 `protobuf:"bytes,17,opt,name=pv_police_b,json=pvPoliceB,proto3" json:"pv_police_b,omitempty"`
	PvGendarmerieB   string                 `protobuf:"bytes,18,opt,name=pv_gendarmerie_b,json=pvGendarmerieB,proto3" json:"pv_gendarmerie_b,omitempty"`
	Status           string                 `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAccidentResponse) Reset() {
	*x = GetAccidentResponse{}
	mi := &file_proto_accident_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccidentResponse) ProtoMessage() {}

func (x *GetAccidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accident_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccidentResponse.ProtoReflect.Descriptor instead.
func (*GetAccidentResponse) Descriptor() ([]byte, []int) {
	return file_proto_accident_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccidentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAccidentResponse) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *GetAccidentResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetAccidentResponse) GetCirconstances() string {
	if x != nil {
		return x.Circonstances
	}
	return ""
}

func (x *GetAccidentResponse) GetVehicleAId() int64 {
	if x != nil {
		return x.VehicleAId
	}
	return 0
}

func (x *GetAccidentResponse) GetDriverAId() int64 {
	if x != nil {
		return x.DriverAId
	}
	return 0
}

func (x *GetAccidentResponse) GetPointDeChocA() string {
	if x != nil {
		return x.PointDeChocA
	}
	return ""
}

func (x *GetAccidentResponse) GetDegatsApparentsA() string {
	if x != nil {
		return x.DegatsApparentsA
	}
	return ""
}

func (x *GetAccidentResponse) GetObservationsA() string {
	if x != nil {
		return x.ObservationsA
	}
	return ""
}

func (x *GetAccidentResponse) GetPvPoliceA() string {
	if x != nil {
		return x.PvPoliceA
	}
	return ""
}

func (x *GetAccidentResponse) GetPvGendarmerieA() string {
	if x != nil {
		return x.PvGendarmerieA
	}
	return ""
}

func (x *GetAccidentResponse) GetVehicleBId() int64 {
	if x != nil {
		return x.VehicleBId
	}
	return 0
}

func (x *GetAccidentResponse) GetDriverBId() int64 {
	if x != nil {
		return x.DriverBId
	}
	return 0
}

func (x *GetAccidentResponse) GetPointDeChocB() string {
	if x != nil {
		return x.PointDeChocB
	}
	return ""
}

func (x *GetAccidentResponse) GetDegatsApparentsB() string {
	if x != nil {
		return x.DegatsApparentsB
	}
	return ""
}

func (x *GetAccidentResponse) GetObservationsB() string {
	if x != nil {
		return x.ObservationsB
	}
	return ""
}

func (x *GetAccidentResponse) GetPvPoliceB() string {
	if x != nil {
		return x.PvPoliceB
	}
	return ""
}

func (x *GetAccidentResponse) GetPvGendarmerieB() string {
	if x != nil {
		return x.PvGendarmerieB
	}
	return ""
}

func (x *GetAccidentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateAccidentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DateTime         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Location         string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Circonstances    string                 `protobuf:"bytes,4,opt,name=circonstances,proto3" json:"circonstances,omitempty"`
	VehicleAId       int64                  `protobuf:"varint,5,opt,name=vehicle_a_id,json=vehicleAId,proto3" json:"vehicle_a_id,omitempty"`
	DriverAId        int64                  `protobuf:"varint,6,opt,name=driver_a_id,json=driverAId,proto3" json:"driver_a_id,omitempty"`
	PointDeChocA     string                 `protobuf:"bytes,7,opt,name=point_de_choc_a,json=pointDeChocA,proto3" json:"point_de_choc_a,omitempty"`
	DegatsApparentsA string                 `protobuf:"bytes,8,opt,name=degats_apparents_a,json=degatsApparentsA,proto3" json:"degats_apparents_a,omitempty"`
	ObservationsA    string                 `protobuf:"bytes,9,opt,name=observations_a,json=observationsA,proto3" json:"observations_a,omitempty"`
	PvPoliceA        string                 `protobuf:"bytes,10,opt,name=pv_police_a,json=pvPoliceA,proto3" json:"pv_police_a,omitempty"`
	PvGendarmerieA   string                 `protobuf:"bytes,11,opt,name=pv_gendarmerie_a,json=pvGendarmerieA,proto3" json:"pv_gendarmerie_a,omitempty"`
	VehicleBId       int64                  `protobuf:"varint,12,opt,name=vehicle_b_id,json=vehicleBId,proto3" json:"vehicle_b_id,omitempty"`
	DriverBId        int64                  `protobuf:"varint,13,opt,name=driver_b_id,json=driverBId,proto3" json:"driver_b_id,omitempty"`
	PointDeChocB     string                 `protobuf:"bytes,14,opt,name=point_de_choc_b,json=pointDeChocB,proto3" json:"point_de_choc_b,omitempty"`
	DegatsApparentsB string                 `protobuf:"bytes,15,opt,name=degats_apparents_b,json=degatsApparentsB,proto3" json:"degats_apparents_b,omitempty"`
	ObservationsB    string                 `protobuf:"bytes,16,opt,name=observations_b,json=observationsB,proto3" json:"observations_b,omitempty"`
	PvPoliceB        string                 `protobuf:"bytes,17,opt,name=pv_police_b,json=pvPoliceB,proto3" json:"pv_police_b,omitempty"`
	PvGendarmerieB   string                 `protobuf:"bytes,18,opt,name=pv_gendarmerie_b,json=pvGendarmerieB,proto3" json:"pv_gendarmerie_b,omitempty"`
	Status           string                 `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateAccidentRequest) Reset() {
	*x = UpdateAccidentRequest{}
	mi := &file_proto_accident_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccidentRequest) ProtoMessage() {}

func (x *UpdateAccidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accident_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccidentRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccidentRequest) Descriptor() ([]byte, []int) {
	return file_proto_accident_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAccidentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAccidentRequest) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *UpdateAccidentRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateAccidentRequest) GetCirconstances() string {
	if x != nil {
		return x.Circonstances
	}
	return ""
}

func (x *UpdateAccidentRequest) GetVehicleAId() int64 {
	if x != nil {
		return x.VehicleAId
	}
	return 0
}

func (x *UpdateAccidentRequest) GetDriverAId() int64 {
	if x != nil {
		return x.DriverAId
	}
	return 0
}

func (x *UpdateAccidentRequest) GetPointDeChocA() string {
	if x != nil {
		return x.PointDeChocA
	}
	return ""
}

func (x *UpdateAccidentRequest) GetDegatsApparentsA() string {
	if x != nil {
		return x.DegatsApparentsA
	}
	return ""
}

func (x *UpdateAccidentRequest) GetObservationsA() string {
	if x != nil {
		return x.ObservationsA
	}
	return ""
}

func (x *UpdateAccidentRequest) GetPvPoliceA() string {
	if x != nil {
		return x.PvPoliceA
	}
	return ""
}

func (x *UpdateAccidentRequest) GetPvGendarmerieA() string {
	if x != nil {
		return x.PvGendarmerieA
	}
	return ""
}

func (x *UpdateAccidentRequest) GetVehicleBId() int64 {
	if x != nil {
		return x.VehicleBId
	}
	return 0
}

func (x *UpdateAccidentRequest) GetDriverBId() int64 {
	if x != nil {
		return x.DriverBId
	}
	return 0
}

func (x *UpdateAccidentRequest) GetPointDeChocB() string {
	if x != nil {
		return x.PointDeChocB
	}
	return ""
}

func (x *UpdateAccidentRequest) GetDegatsApparentsB() string {
	if x != nil {
		return x.DegatsApparentsB
	}
	return ""
}

func (x *UpdateAccidentRequest) GetObservationsB() string {
	if x != nil {
		return x.ObservationsB
	}
	return ""
}

func (x *UpdateAccidentRequest) GetPvPoliceB() string {
	if x != nil {
		return x.PvPoliceB
	}
	return ""
}

func (x *UpdateAccidentRequest) GetPvGendarmerieB() string {
	if x != nil {
		return x.PvGendarmerieB
	}
	return ""
}

func (x *UpdateAccidentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateAccidentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DateTime         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_time,json=dateTime,proto3" json:"date_time,omitempty"`
	Location         string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Circonstances    string                 `protobuf:"bytes,4,opt,name=circonstances,proto3" json:"circonstances,omitempty"`
	VehicleAId       int64                  `protobuf:"varint,5,opt,name=vehicle_a_id,json=vehicleAId,proto3" json:"vehicle_a_id,omitempty"`
	DriverAId        int64                  `protobuf:"varint,6,opt,name=driver_a_id,json=driverAId,proto3" json:"driver_a_id,omitempty"`
	PointDeChocA     string                 `protobuf:"bytes,7,opt,name=point_de_choc_a,json=pointDeChocA,proto3" json:"point_de_choc_a,omitempty"`
	DegatsApparentsA string                 `protobuf:"bytes,8,opt,name=degats_apparents_a,json=degatsApparentsA,proto3" json:"degats_apparents_a,omitempty"`
	ObservationsA    string                 `protobuf:"bytes,9,opt,name=observations_a,json=observationsA,proto3" json:"observations_a,omitempty"`
	PvPoliceA        string                 `protobuf:"bytes,10,opt,name=pv_police_a,json=pvPoliceA,proto3" json:"pv_police_a,omitempty"`
	PvGendarmerieA   string                 `protobuf:"bytes,11,opt,name=pv_gendarmerie_a,json=pvGendarmerieA,proto3" json:"pv_gendarmerie_a,omitempty"`
	VehicleBId       int64                  `protobuf:"varint,12,opt,name=vehicle_b_id,json=vehicleBId,proto3" json:"vehicle_b_id,omitempty"`
	DriverBId        int64                  `protobuf:"varint,13,opt,name=driver_b_id,json=driverBId,proto3" json:"driver_b_id,omitempty"`
	PointDeChocB     string                 `protobuf:"bytes,14,opt,name=point_de_choc_b,json=pointDeChocB,proto3" json:"point_de_choc_b,omitempty"`
	DegatsApparentsB string                 `protobuf:"bytes,15,opt,name=degats_apparents_b,json=degatsApparentsB,proto3" json:"degats_apparents_b,omitempty"`
	ObservationsB    string                 `protobuf:"bytes,16,opt,name=observations_b,json=observationsB,proto3" json:"observations_b,omitempty"`
	PvPoliceB        string                 `protobuf:"bytes,17,opt,name=pv_police_b,json=pvPoliceB,proto3" json:"pv_police_b,omitempty"`
	PvGendarmerieB   string                 `protobuf:"bytes,18,opt,name=pv_gendarmerie_b,json=pvGendarmerieB,proto3" json:"pv_gendarmerie_b,omitempty"`
	Status           string                 `protobuf:"bytes,19,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateAccidentResponse) Reset() {
	*x = UpdateAccidentResponse{}
	mi := &file_proto_accident_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccidentResponse) ProtoMessage() {}

func (x *UpdateAccidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accident_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccidentResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccidentResponse) Descriptor() ([]byte, []int) {
	return file_proto_accident_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccidentResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAccidentResponse) GetDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTime
	}
	return nil
}

func (x *UpdateAccidentResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateAccidentResponse) GetCirconstances() string {
	if x != nil {
		return x.Circonstances
	}
	return ""
}

func (x *UpdateAccidentResponse) GetVehicleAId() int64 {
	if x != nil {
		return x.VehicleAId
	}
	return 0
}

func (x *UpdateAccidentResponse) GetDriverAId() int64 {
	if x != nil {
		return x.DriverAId
	}
	return 0
}

func (x *UpdateAccidentResponse) GetPointDeChocA() string {
	if x != nil {
		return x.PointDeChocA
	}
	return ""
}

func (x *UpdateAccidentResponse) GetDegatsApparentsA() string {
	if x != nil {
		return x.DegatsApparentsA
	}
	return ""
}

func (x *UpdateAccidentResponse) GetObservationsA() string {
	if x != nil {
		return x.ObservationsA
	}
	return ""
}

func (x *UpdateAccidentResponse) GetPvPoliceA() string {
	if x != nil {
		return x.PvPoliceA
	}
	return ""
}

func (x *UpdateAccidentResponse) GetPvGendarmerieA() string {
	if x != nil {
		return x.PvGendarmerieA
	}
	return ""
}

func (x *UpdateAccidentResponse) GetVehicleBId() int64 {
	if x != nil {
		return x.VehicleBId
	}
	return 0
}

func (x *UpdateAccidentResponse) GetDriverBId() int64 {
	if x != nil {
		return x.DriverBId
	}
	return 0
}

func (x *UpdateAccidentResponse) GetPointDeChocB() string {
	if x != nil {
		return x.PointDeChocB
	}
	return ""
}

func (x *UpdateAccidentResponse) GetDegatsApparentsB() string {
	if x != nil {
		return x.DegatsApparentsB
	}
	return ""
}

func (x *UpdateAccidentResponse) GetObservationsB() string {
	if x != nil {
		return x.ObservationsB
	}
	return ""
}

func (x *UpdateAccidentResponse) GetPvPoliceB() string {
	if x != nil {
		return x.PvPoliceB
	}
	return ""
}

func (x *UpdateAccidentResponse) GetPvGendarmerieB() string {
	if x != nil {
		return x.PvGendarmerieB
	}
	return ""
}

func (x *UpdateAccidentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteAccidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccidentRequest) Reset() {
	*x = DeleteAccidentRequest{}
	mi := &file_proto_accident_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccidentRequest) ProtoMessage() {}

func (x *DeleteAccidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accident_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccidentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccidentRequest) Descriptor() ([]byte, []int) {
	return file_proto_accident_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAccidentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAccidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccidentResponse) Reset() {
	*x = DeleteAccidentResponse{}
	mi := &file_proto_accident_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccidentResponse) ProtoMessage() {}

func (x *DeleteAccidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accident_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccidentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccidentResponse) Descriptor() ([]byte, []int) {
	return file_proto_accident_proto_rawDescGZIP(), []int{8}
}

var File_proto_accident_proto protoreflect.FileDescriptor

const file_proto_accident_proto_rawDesc = "" +
	"\n" +
	"\x14proto/accident.proto\x12\baccident\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x05\n" +
	"\bAccident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\tdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12$\n" +
	"\rcirconstances\x18\x04 \x01(\tR\rcirconstances\x12 \n" +
	"\fvehicle_a_id\x18\x05 \x01(\x03R\n" +
	"vehicleAId\x12\x1e\n" +
	"\vdriver_a_id\x18\x06 \x01(\x03R\tdriverAId\x12%\n" +
	"\x0fpoint_de_choc_a\x18\a \x01(\tR\fpointDeChocA\x12,\n" +
	"\x12degats_apparents_a\x18\b \x01(\tR\x10degatsApparentsA\x12%\n" +
	"\x0eobservations_a\x18\t \x01(\tR\robservationsA\x12\x1e\n" +
	"\vpv_police_a\x18\n" +
	" \x01(\tR\tpvPoliceA\x12(\n" +
	"\x10pv_gendarmerie_a\x18\v \x01(\tR\x0epvGendarmerieA\x12 \n" +
	"\fvehicle_b_id\x18\f \x01(\x03R\n" +
	"vehicleBId\x12\x1e\n" +
	"\vdriver_b_id\x18\r \x01(\x03R\tdriverBId\x12%\n" +
	"\x0fpoint_de_choc_b\x18\x0e \x01(\tR\fpointDeChocB\x12,\n" +
	"\x12degats_apparents_b\x18\x0f \x01(\tR\x10degatsApparentsB\x12%\n" +
	"\x0eobservations_b\x18\x10 \x01(\tR\robservationsB\x12\x1e\n" +
	"\vpv_police_b\x18\x11 \x01(\tR\tpvPoliceB\x12(\n" +
	"\x10pv_gendarmerie_b\x18\x12 \x01(\tR\x0epvGendarmerieB\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\"\xba\x05\n" +
	"\x15CreateAccidentRequest\x127\n" +
	"\tdate_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12$\n" +
	"\rcirconstances\x18\x03 \x01(\tR\rcirconstances\x12 \n" +
	"\fvehicle_a_id\x18\x04 \x01(\x03R\n" +
	"vehicleAId\x12\x1e\n" +
	"\vdriver_a_id\x18\x05 \x01(\x03R\tdriverAId\x12%\n" +
	"\x0fpoint_de_choc_a\x18\x06 \x01(\tR\fpointDeChocA\x12,\n" +
	"\x12degats_apparents_a\x18\a \x01(\tR\x10degatsApparentsA\x12%\n" +
	"\x0eobservations_a\x18\b \x01(\tR\robservationsA\x12\x1e\n" +
	"\vpv_police_a\x18\t \x01(\tR\tpvPoliceA\x12(\n" +
	"\x10pv_gendarmerie_a\x18\n" +
	" \x01(\tR\x0epvGendarmerieA\x12 \n" +
	"\fvehicle_b_id\x18\v \x01(\x03R\n" +
	"vehicleBId\x12\x1e\n" +
	"\vdriver_b_id\x18\f \x01(\x03R\tdriverBId\x12%\n" +
	"\x0fpoint_de_choc_b\x18\r \x01(\tR\fpointDeChocB\x12,\n" +
	"\x12degats_apparents_b\x18\x0e \x01(\tR\x10degatsApparentsB\x12%\n" +
	"\x0eobservations_b\x18\x0f \x01(\tR\robservationsB\x12\x1e\n" +
	"\vpv_police_b\x18\x10 \x01(\tR\tpvPoliceB\x12(\n" +
	"\x10pv_gendarmerie_b\x18\x11 \x01(\tR\x0epvGendarmerieB\x12\x16\n" +
	"\x06status\x18\x12 \x01(\tR\x06status\"\xcb\x05\n" +
	"\x16CreateAccidentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\tdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12$\n" +
	"\rcirconstances\x18\x04 \x01(\tR\rcirconstances\x12 \n" +
	"\fvehicle_a_id\x18\x05 \x01(\x03R\n" +
	"vehicleAId\x12\x1e\n" +
	"\vdriver_a_id\x18\x06 \x01(\x03R\tdriverAId\x12%\n" +
	"\x0fpoint_de_choc_a\x18\a \x01(\tR\fpointDeChocA\x12,\n" +
	"\x12degats_apparents_a\x18\b \x01(\tR\x10degatsApparentsA\x12%\n" +
	"\x0eobservations_a\x18\t \x01(\tR\robservationsA\x12\x1e\n" +
	"\vpv_police_a\x18\n" +
	" \x01(\tR\tpvPoliceA\x12(\n" +
	"\x10pv_gendarmerie_a\x18\v \x01(\tR\x0epvGendarmerieA\x12 \n" +
	"\fvehicle_b_id\x18\f \x01(\x03R\n" +
	"vehicleBId\x12\x1e\n" +
	"\vdriver_b_id\x18\r \x01(\x03R\tdriverBId\x12%\n" +
	"\x0fpoint_de_choc_b\x18\x0e \x01(\tR\fpointDeChocB\x12,\n" +
	"\x12degats_apparents_b\x18\x0f \x01(\tR\x10degatsApparentsB\x12%\n" +
	"\x0eobservations_b\x18\x10 \x01(\tR\robservationsB\x12\x1e\n" +
	"\vpv_police_b\x18\x11 \x01(\tR\tpvPoliceB\x12(\n" +
	"\x10pv_gendarmerie_b\x18\x12 \x01(\tR\x0epvGendarmerieB\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\"$\n" +
	"\x12GetAccidentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xc8\x05\n" +
	"\x13GetAccidentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\tdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12$\n" +
	"\rcirconstances\x18\x04 \x01(\tR\rcirconstances\x12 \n" +
	"\fvehicle_a_id\x18\x05 \x01(\x03R\n" +
	"vehicleAId\x12\x1e\n" +
	"\vdriver_a_id\x18\x06 \x01(\x03R\tdriverAId\x12%\n" +
	"\x0fpoint_de_choc_a\x18\a \x01(\tR\fpointDeChocA\x12,\n" +
	"\x12degats_apparents_a\x18\b \x01(\tR\x10degatsApparentsA\x12%\n" +
	"\x0eobservations_a\x18\t \x01(\tR\robservationsA\x12\x1e\n" +
	"\vpv_police_a\x18\n" +
	" \x01(\tR\tpvPoliceA\x12(\n" +
	"\x10pv_gendarmerie_a\x18\v \x01(\tR\x0epvGendarmerieA\x12 \n" +
	"\fvehicle_b_id\x18\f \x01(\x03R\n" +
	"vehicleBId\x12\x1e\n" +
	"\vdriver_b_id\x18\r \x01(\x03R\tdriverBId\x12%\n" +
	"\x0fpoint_de_choc_b\x18\x0e \x01(\tR\fpointDeChocB\x12,\n" +
	"\x12degats_apparents_b\x18\x0f \x01(\tR\x10degatsApparentsB\x12%\n" +
	"\x0eobservations_b\x18\x10 \x01(\tR\robservationsB\x12\x1e\n" +
	"\vpv_police_b\x18\x11 \x01(\tR\tpvPoliceB\x12(\n" +
	"\x10pv_gendarmerie_b\x18\x12 \x01(\tR\x0epvGendarmerieB\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\"\xca\x05\n" +
	"\x15UpdateAccidentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\tdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12$\n" +
	"\rcirconstances\x18\x04 \x01(\tR\rcirconstances\x12 \n" +
	"\fvehicle_a_id\x18\x05 \x01(\x03R\n" +
	"vehicleAId\x12\x1e\n" +
	"\vdriver_a_id\x18\x06 \x01(\x03R\tdriverAId\x12%\n" +
	"\x0fpoint_de_choc_a\x18\a \x01(\tR\fpointDeChocA\x12,\n" +
	"\x12degats_apparents_a\x18\b \x01(\tR\x10degatsApparentsA\x12%\n" +
	"\x0eobservations_a\x18\t \x01(\tR\robservationsA\x12\x1e\n" +
	"\vpv_police_a\x18\n" +
	" \x01(\tR\tpvPoliceA\x12(\n" +
	"\x10pv_gendarmerie_a\x18\v \x01(\tR\x0epvGendarmerieA\x12 \n" +
	"\fvehicle_b_id\x18\f \x01(\x03R\n" +
	"vehicleBId\x12\x1e\n" +
	"\vdriver_b_id\x18\r \x01(\x03R\tdriverBId\x12%\n" +
	"\x0fpoint_de_choc_b\x18\x0e \x01(\tR\fpointDeChocB\x12,\n" +
	"\x12degats_apparents_b\x18\x0f \x01(\tR\x10degatsApparentsB\x12%\n" +
	"\x0eobservations_b\x18\x10 \x01(\tR\robservationsB\x12\x1e\n" +
	"\vpv_police_b\x18\x11 \x01(\tR\tpvPoliceB\x12(\n" +
	"\x10pv_gendarmerie_b\x18\x12 \x01(\tR\x0epvGendarmerieB\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\"\xcb\x05\n" +
	"\x16UpdateAccidentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x127\n" +
	"\tdate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdateTime\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12$\n" +
	"\rcirconstances\x18\x04 \x01(\tR\rcirconstances\x12 \n" +
	"\fvehicle_a_id\x18\x05 \x01(\x03R\n" +
	"vehicleAId\x12\x1e\n" +
	"\vdriver_a_id\x18\x06 \x01(\x03R\tdriverAId\x12%\n" +
	"\x0fpoint_de_choc_a\x18\a \x01(\tR\fpointDeChocA\x12,\n" +
	"\x12degats_apparents_a\x18\b \x01(\tR\x10degatsApparentsA\x12%\n" +
	"\x0eobservations_a\x18\t \x01(\tR\robservationsA\x12\x1e\n" +
	"\vpv_police_a\x18\n" +
	" \x01(\tR\tpvPoliceA\x12(\n" +
	"\x10pv_gendarmerie_a\x18\v \x01(\tR\x0epvGendarmerieA\x12 \n" +
	"\fvehicle_b_id\x18\f \x01(\x03R\n" +
	"vehicleBId\x12\x1e\n" +
	"\vdriver_b_id\x18\r \x01(\x03R\tdriverBId\x12%\n" +
	"\x0fpoint_de_choc_b\x18\x0e \x01(\tR\fpointDeChocB\x12,\n" +
	"\x12degats_apparents_b\x18\x0f \x01(\tR\x10degatsApparentsB\x12%\n" +
	"\x0eobservations_b\x18\x10 \x01(\tR\robservationsB\x12\x1e\n" +
	"\vpv_police_b\x18\x11 \x01(\tR\tpvPoliceB\x12(\n" +
	"\x10pv_gendarmerie_b\x18\x12 \x01(\tR\x0epvGendarmerieB\x12\x16\n" +
	"\x06status\x18\x13 \x01(\tR\x06status\"'\n" +
	"\x15DeleteAccidentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x18\n" +
	"\x16DeleteAccidentResponse2\xdc\x02\n" +
	"\x0fAccidentService\x12S\n" +
	"\x0eCreateAccident\x12\x1f.accident.CreateAccidentRequest\x1a .accident.CreateAccidentResponse\x12J\n" +
	"\vGetAccident\x12\x1c.accident.GetAccidentRequest\x1a\x1d.accident.GetAccidentResponse\x12S\n" +
	"\x0eUpdateAccident\x12\x1f.accident.UpdateAccidentRequest\x1a .accident.UpdateAccidentResponse\x12S\n" +
	"\x0eDeleteAccident\x12\x1f.accident.DeleteAccidentRequest\x1a .accident.DeleteAccidentResponseB\x18Z\x16/rpc/accident;accidentb\x06proto3"

var (
	file_proto_accident_proto_rawDescOnce sync.Once
	file_proto_accident_proto_rawDescData []byte
)

func file_proto_accident_proto_rawDescGZIP() []byte {
	file_proto_accident_proto_rawDescOnce.Do(func() {
		file_proto_accident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accident_proto_rawDesc), len(file_proto_accident_proto_rawDesc)))
	})
	return file_proto_accident_proto_rawDescData
}

var file_proto_accident_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_accident_proto_goTypes = []any{
	(*Accident)(nil),               // 0: accident.Accident
	(*CreateAccidentRequest)(nil),  // 1: accident.CreateAccidentRequest
	(*CreateAccidentResponse)(nil), // 2: accident.CreateAccidentResponse
	(*GetAccidentRequest)(nil),     // 3: accident.GetAccidentRequest
	(*GetAccidentResponse)(nil),    // 4: accident.GetAccidentResponse
	(*UpdateAccidentRequest)(nil),  // 5: accident.UpdateAccidentRequest
	(*UpdateAccidentResponse)(nil), // 6: accident.UpdateAccidentResponse
	(*DeleteAccidentRequest)(nil),  // 7: accident.DeleteAccidentRequest
	(*DeleteAccidentResponse)(nil), // 8: accident.DeleteAccidentResponse
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_proto_accident_proto_depIdxs = []int32{
	9,  // 0: accident.Accident.date_time:type_name -> google.protobuf.Timestamp
	9,  // 1: accident.CreateAccidentRequest.date_time:type_name -> google.protobuf.Timestamp
	9,  // 2: accident.CreateAccidentResponse.date_time:type_name -> google.protobuf.Timestamp
	9,  // 3: accident.GetAccidentResponse.date_time:type_name -> google.protobuf.Timestamp
	9,  // 4: accident.UpdateAccidentRequest.date_time:type_name -> google.protobuf.Timestamp
	9,  // 5: accident.UpdateAccidentResponse.date_time:type_name -> google.protobuf.Timestamp
	1,  // 6: accident.AccidentService.CreateAccident:input_type -> accident.CreateAccidentRequest
	3,  // 7: accident.AccidentService.GetAccident:input_type -> accident.GetAccidentRequest
	5,  // 8: accident.AccidentService.UpdateAccident:input_type -> accident.UpdateAccidentRequest
	7,  // 9: accident.AccidentService.DeleteAccident:input_type -> accident.DeleteAccidentRequest
	2,  // 10: accident.AccidentService.CreateAccident:output_type -> accident.CreateAccidentResponse
	4,  // 11: accident.AccidentService.GetAccident:output_type -> accident.GetAccidentResponse
	6,  // 12: accident.AccidentService.UpdateAccident:output_type -> accident.UpdateAccidentResponse
	8,  // 13: accident.AccidentService.DeleteAccident:output_type -> accident.DeleteAccidentResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_accident_proto_init() }
func file_proto_accident_proto_init() {
	if File_proto_accident_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accident_proto_rawDesc), len(file_proto_accident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_accident_proto_goTypes,
		DependencyIndexes: file_proto_accident_proto_depIdxs,
		MessageInfos:      file_proto_accident_proto_msgTypes,
	}.Build()
	File_proto_accident_proto = out.File
	file_proto_accident_proto_goTypes = nil
	file_proto_accident_proto_depIdxs = nil
}
