// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/vehicle.proto

package vehicle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vehicle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId        int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Brand          string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year           int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	EnginePower    string                 `protobuf:"bytes,6,opt,name=engine_power,json=enginePower,proto3" json:"engine_power,omitempty"`
	Seats          int32                  `protobuf:"varint,7,opt,name=seats,proto3" json:"seats,omitempty"`
	ChassisNumber  string                 `protobuf:"bytes,8,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	LicensePlate   string                 `protobuf:"bytes,9,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Energy         string                 `protobuf:"bytes,10,opt,name=energy,proto3" json:"energy,omitempty"`
	VehicleType    string                 `protobuf:"bytes,11,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Wilaya         int32                  `protobuf:"varint,12,opt,name=wilaya,proto3" json:"wilaya,omitempty"`
	ValeurVenale   float64                `protobuf:"fixed64,13,opt,name=valeur_venale,json=valeurVenale,proto3" json:"valeur_venale,omitempty"`
	PaiementCcp    bool                   `protobuf:"varint,14,opt,name=paiement_ccp,json=paiementCcp,proto3" json:"paiement_ccp,omitempty"`
	Moins_25Ans    bool                   `protobuf:"varint,15,opt,name=moins_25_ans,json=moins25Ans,proto3" json:"moins_25_ans,omitempty"`
	PermisPlus_1An bool                   `protobuf:"varint,16,opt,name=permis_plus_1an,json=permisPlus1an,proto3" json:"permis_plus_1an,omitempty"`
	CarteGrisePath string                 `protobuf:"bytes,17,opt,name=carte_grise_path,json=carteGrisePath,proto3" json:"carte_grise_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_proto_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *Vehicle) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vehicle) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Vehicle) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Vehicle) GetEnginePower() string {
	if x != nil {
		return x.EnginePower
	}
	return ""
}

func (x *Vehicle) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *Vehicle) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *Vehicle) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Vehicle) GetEnergy() string {
	if x != nil {
		return x.Energy
	}
	return ""
}

func (x *Vehicle) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *Vehicle) GetWilaya() int32 {
	if x != nil {
		return x.Wilaya
	}
	return 0
}

func (x *Vehicle) GetValeurVenale() float64 {
	if x != nil {
		return x.ValeurVenale
	}
	return 0
}

func (x *Vehicle) GetPaiementCcp() bool {
	if x != nil {
		return x.PaiementCcp
	}
	return false
}

func (x *Vehicle) GetMoins_25Ans() bool {
	if x != nil {
		return x.Moins_25Ans
	}
	return false
}

func (x *Vehicle) GetPermisPlus_1An() bool {
	if x != nil {
		return x.PermisPlus_1An
	}
	return false
}

func (x *Vehicle) GetCarteGrisePath() string {
	if x != nil {
		return x.CarteGrisePath
	}
	return ""
}

type CreateVehicleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerId        int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Brand          string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model          string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year           int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	EnginePower    string                 `protobuf:"bytes,5,opt,name=engine_power,json=enginePower,proto3" json:"engine_power,omitempty"`
	Seats          int32                  `protobuf:"varint,6,opt,name=seats,proto3" json:"seats,omitempty"`
	ChassisNumber  string                 `protobuf:"bytes,7,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	LicensePlate   string                 `protobuf:"bytes,8,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Energy         string                 `protobuf:"bytes,9,opt,name=energy,proto3" json:"energy,omitempty"`
	VehicleType    string                 `protobuf:"bytes,10,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Wilaya         int32                  `protobuf:"varint,11,opt,name=wilaya,proto3" json:"wilaya,omitempty"`
	ValeurVenale   float64                `protobuf:"fixed64,12,opt,name=valeur_venale,json=valeurVenale,proto3" json:"valeur_venale,omitempty"`
	PaiementCcp    bool                   `protobuf:"varint,13,opt,name=paiement_ccp,json=paiementCcp,proto3" json:"paiement_ccp,omitempty"`
	Moins25Ans     bool                   `protobuf:"varint,14,opt,name=moins25_ans,json=moins25Ans,proto3" json:"moins25_ans,omitempty"`
	PermisPlus1An  bool                   `protobuf:"varint,15,opt,name=permis_plus1_an,json=permisPlus1An,proto3" json:"permis_plus1_an,omitempty"`
	CarteGrisePath string                 `protobuf:"bytes,16,opt,name=carte_grise_path,json=carteGrisePath,proto3" json:"carte_grise_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVehicleRequest) Reset() {
	*x = CreateVehicleRequest{}
	mi := &file_proto_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleRequest) ProtoMessage() {}

func (x *CreateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleRequest.ProtoReflect.Descriptor instead.
func (*CreateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVehicleRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateVehicleRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateVehicleRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateVehicleRequest) GetEnginePower() string {
	if x != nil {
		return x.EnginePower
	}
	return ""
}

func (x *CreateVehicleRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *CreateVehicleRequest) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *CreateVehicleRequest) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *CreateVehicleRequest) GetEnergy() string {
	if x != nil {
		return x.Energy
	}
	return ""
}

func (x *CreateVehicleRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CreateVehicleRequest) GetWilaya() int32 {
	if x != nil {
		return x.Wilaya
	}
	return 0
}

func (x *CreateVehicleRequest) GetValeurVenale() float64 {
	if x != nil {
		return x.ValeurVenale
	}
	return 0
}

func (x *CreateVehicleRequest) GetPaiementCcp() bool {
	if x != nil {
		return x.PaiementCcp
	}
	return false
}

func (x *CreateVehicleRequest) GetMoins25Ans() bool {
	if x != nil {
		return x.Moins25Ans
	}
	return false
}

func (x *CreateVehicleRequest) GetPermisPlus1An() bool {
	if x != nil {
		return x.PermisPlus1An
	}
	return false
}

func (x *CreateVehicleRequest) GetCarteGrisePath() string {
	if x != nil {
		return x.CarteGrisePath
	}
	return ""
}

type CreateVehicleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId        int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Brand          string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year           int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	EnginePower    string                 `protobuf:"bytes,6,opt,name=engine_power,json=enginePower,proto3" json:"engine_power,omitempty"`
	Seats          int32                  `protobuf:"varint,7,opt,name=seats,proto3" json:"seats,omitempty"`
	ChassisNumber  string                 `protobuf:"bytes,8,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	LicensePlate   string                 `protobuf:"bytes,9,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Energy         string                 `protobuf:"bytes,10,opt,name=energy,proto3" json:"energy,omitempty"`
	VehicleType    string                 `protobuf:"bytes,11,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Wilaya         int32                  `protobuf:"varint,12,opt,name=wilaya,proto3" json:"wilaya,omitempty"`
	ValeurVenale   float64                `protobuf:"fixed64,13,opt,name=valeur_venale,json=valeurVenale,proto3" json:"valeur_venale,omitempty"`
	PaiementCcp    bool                   `protobuf:"varint,14,opt,name=paiement_ccp,json=paiementCcp,proto3" json:"paiement_ccp,omitempty"`
	Moins_25Ans    bool                   `protobuf:"varint,15,opt,name=moins_25_ans,json=moins25Ans,proto3" json:"moins_25_ans,omitempty"`
	PermisPlus_1An bool                   `protobuf:"varint,16,opt,name=permis_plus_1an,json=permisPlus1an,proto3" json:"permis_plus_1an,omitempty"`
	CarteGrisePath string                 `protobuf:"bytes,17,opt,name=carte_grise_path,json=carteGrisePath,proto3" json:"carte_grise_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVehicleResponse) Reset() {
	*x = CreateVehicleResponse{}
	mi := &file_proto_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleResponse) ProtoMessage() {}

func (x *CreateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleResponse.ProtoReflect.Descriptor instead.
func (*CreateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVehicleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateVehicleResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateVehicleResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateVehicleResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateVehicleResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateVehicleResponse) GetEnginePower() string {
	if x != nil {
		return x.EnginePower
	}
	return ""
}

func (x *CreateVehicleResponse) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *CreateVehicleResponse) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *CreateVehicleResponse) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *CreateVehicleResponse) GetEnergy() string {
	if x != nil {
		return x.Energy
	}
	return ""
}

func (x *CreateVehicleResponse) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CreateVehicleResponse) GetWilaya() int32 {
	if x != nil {
		return x.Wilaya
	}
	return 0
}

func (x *CreateVehicleResponse) GetValeurVenale() float64 {
	if x != nil {
		return x.ValeurVenale
	}
	return 0
}

func (x *CreateVehicleResponse) GetPaiementCcp() bool {
	if x != nil {
		return x.PaiementCcp
	}
	return false
}

func (x *CreateVehicleResponse) GetMoins_25Ans() bool {
	if x != nil {
		return x.Moins_25Ans
	}
	return false
}

func (x *CreateVehicleResponse) GetPermisPlus_1An() bool {
	if x != nil {
		return x.PermisPlus_1An
	}
	return false
}

func (x *CreateVehicleResponse) GetCarteGrisePath() string {
	if x != nil {
		return x.CarteGrisePath
	}
	return ""
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_proto_vehicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_proto_rawDescGZIP(), []int{3}
}

func (x *GetVehicleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetVehicleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId        int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Brand          string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year           int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	EnginePower    string                 `protobuf:"bytes,6,opt,name=engine_power,json=enginePower,proto3" json:"engine_power,omitempty"`
	Seats          int32                  `protobuf:"varint,7,opt,name=seats,proto3" json:"seats,omitempty"`
	ChassisNumber  string                 `protobuf:"bytes,8,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	LicensePlate   string                 `protobuf:"bytes,9,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Energy         string                 `protobuf:"bytes,10,opt,name=energy,proto3" json:"energy,omitempty"`
	VehicleType    string                 `protobuf:"bytes,11,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Wilaya         int32                  `protobuf:"varint,12,opt,name=wilaya,proto3" json:"wilaya,omitempty"`
	ValeurVenale   float64                `protobuf:"fixed64,13,opt,name=valeur_venale,json=valeurVenale,proto3" json:"valeur_venale,omitempty"`
	PaiementCcp    bool                   `protobuf:"varint,14,opt,name=paiement_ccp,json=paiementCcp,proto3" json:"paiement_ccp,omitempty"`
	Moins_25Ans    bool                   `protobuf:"varint,15,opt,name=moins_25_ans,json=moins25Ans,proto3" json:"moins_25_ans,omitempty"`
	PermisPlus_1An bool                   `protobuf:"varint,16,opt,name=permis_plus_1an,json=permisPlus1an,proto3" json:"permis_plus_1an,omitempty"`
	CarteGrisePath string                 `protobuf:"bytes,17,opt,name=carte_grise_path,json=carteGrisePath,proto3" json:"carte_grise_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVehicleResponse) Reset() {
	*x = GetVehicleResponse{}
	mi := &file_proto_vehicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleResponse) ProtoMessage() {}

func (x *GetVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_proto_rawDescGZIP(), []int{4}
}

func (x *GetVehicleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetVehicleResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GetVehicleResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *GetVehicleResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GetVehicleResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetVehicleResponse) GetEnginePower() string {
	if x != nil {
		return x.EnginePower
	}
	return ""
}

func (x *GetVehicleResponse) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *GetVehicleResponse) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *GetVehicleResponse) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *GetVehicleResponse) GetEnergy() string {
	if x != nil {
		return x.Energy
	}
	return ""
}

func (x *GetVehicleResponse) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *GetVehicleResponse) GetWilaya() int32 {
	if x != nil {
		return x.Wilaya
	}
	return 0
}

func (x *GetVehicleResponse) GetValeurVenale() float64 {
	if x != nil {
		return x.ValeurVenale
	}
	return 0
}

func (x *GetVehicleResponse) GetPaiementCcp() bool {
	if x != nil {
		return x.PaiementCcp
	}
	return false
}

func (x *GetVehicleResponse) GetMoins_25Ans() bool {
	if x != nil {
		return x.Moins_25Ans
	}
	return false
}

func (x *GetVehicleResponse) GetPermisPlus_1An() bool {
	if x != nil {
		return x.PermisPlus_1An
	}
	return false
}

func (x *GetVehicleResponse) GetCarteGrisePath() string {
	if x != nil {
		return x.CarteGrisePath
	}
	return ""
}

type UpdateVehicleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId        int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Brand          string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year           int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	EnginePower    string                 `protobuf:"bytes,6,opt,name=engine_power,json=enginePower,proto3" json:"engine_power,omitempty"`
	Seats          int32                  `protobuf:"varint,7,opt,name=seats,proto3" json:"seats,omitempty"`
	ChassisNumber  string                 `protobuf:"bytes,8,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	LicensePlate   string                 `protobuf:"bytes,9,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Energy         string                 `protobuf:"bytes,10,opt,name=energy,proto3" json:"energy,omitempty"`
	VehicleType    string                 `protobuf:"bytes,11,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Wilaya         int32                  `protobuf:"varint,12,opt,name=wilaya,proto3" json:"wilaya,omitempty"`
	ValeurVenale   float64                `protobuf:"fixed64,13,opt,name=valeur_venale,json=valeurVenale,proto3" json:"valeur_venale,omitempty"`
	PaiementCcp    bool                   `protobuf:"varint,14,opt,name=paiement_ccp,json=paiementCcp,proto3" json:"paiement_ccp,omitempty"`
	Moins_25Ans    bool                   `protobuf:"varint,15,opt,name=moins_25_ans,json=moins25Ans,proto3" json:"moins_25_ans,omitempty"`
	PermisPlus_1An bool                   `protobuf:"varint,16,opt,name=permis_plus_1an,json=permisPlus1an,proto3" json:"permis_plus_1an,omitempty"`
	CarteGrisePath string                 `protobuf:"bytes,17,opt,name=carte_grise_path,json=carteGrisePath,proto3" json:"carte_grise_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateVehicleRequest) Reset() {
	*x = UpdateVehicleRequest{}
	mi := &file_proto_vehicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleRequest) ProtoMessage() {}

func (x *UpdateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateVehicleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVehicleRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *UpdateVehicleRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateVehicleRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpdateVehicleRequest) GetEnginePower() string {
	if x != nil {
		return x.EnginePower
	}
	return ""
}

func (x *UpdateVehicleRequest) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *UpdateVehicleRequest) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *UpdateVehicleRequest) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *UpdateVehicleRequest) GetEnergy() string {
	if x != nil {
		return x.Energy
	}
	return ""
}

func (x *UpdateVehicleRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *UpdateVehicleRequest) GetWilaya() int32 {
	if x != nil {
		return x.Wilaya
	}
	return 0
}

func (x *UpdateVehicleRequest) GetValeurVenale() float64 {
	if x != nil {
		return x.ValeurVenale
	}
	return 0
}

func (x *UpdateVehicleRequest) GetPaiementCcp() bool {
	if x != nil {
		return x.PaiementCcp
	}
	return false
}

func (x *UpdateVehicleRequest) GetMoins_25Ans() bool {
	if x != nil {
		return x.Moins_25Ans
	}
	return false
}

func (x *UpdateVehicleRequest) GetPermisPlus_1An() bool {
	if x != nil {
		return x.PermisPlus_1An
	}
	return false
}

func (x *UpdateVehicleRequest) GetCarteGrisePath() string {
	if x != nil {
		return x.CarteGrisePath
	}
	return ""
}

type UpdateVehicleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId        int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Brand          string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model          string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year           int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	EnginePower    string                 `protobuf:"bytes,6,opt,name=engine_power,json=enginePower,proto3" json:"engine_power,omitempty"`
	Seats          int32                  `protobuf:"varint,7,opt,name=seats,proto3" json:"seats,omitempty"`
	ChassisNumber  string                 `protobuf:"bytes,8,opt,name=chassis_number,json=chassisNumber,proto3" json:"chassis_number,omitempty"`
	LicensePlate   string                 `protobuf:"bytes,9,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Energy         string                 `protobuf:"bytes,10,opt,name=energy,proto3" json:"energy,omitempty"`
	VehicleType    string                 `protobuf:"bytes,11,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Wilaya         int32                  `protobuf:"varint,12,opt,name=wilaya,proto3" json:"wilaya,omitempty"`
	ValeurVenale   float64                `protobuf:"fixed64,13,opt,name=valeur_venale,json=valeurVenale,proto3" json:"valeur_venale,omitempty"`
	PaiementCcp    bool                   `protobuf:"varint,14,opt,name=paiement_ccp,json=paiementCcp,proto3" json:"paiement_ccp,omitempty"`
	Moins_25Ans    bool                   `protobuf:"varint,15,opt,name=moins_25_ans,json=moins25Ans,proto3" json:"moins_25_ans,omitempty"`
	PermisPlus_1An bool                   `protobuf:"varint,16,opt,name=permis_plus_1an,json=permisPlus1an,proto3" json:"permis_plus_1an,omitempty"`
	CarteGrisePath string                 `protobuf:"bytes,17,opt,name=carte_grise_path,json=carteGrisePath,proto3" json:"carte_grise_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateVehicleResponse) Reset() {
	*x = UpdateVehicleResponse{}
	mi := &file_proto_vehicle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleResponse) ProtoMessage() {}

func (x *UpdateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleResponse.ProtoReflect.Descriptor instead.
func (*UpdateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVehicleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVehicleResponse) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *UpdateVehicleResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateVehicleResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateVehicleResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpdateVehicleResponse) GetEnginePower() string {
	if x != nil {
		return x.EnginePower
	}
	return ""
}

func (x *UpdateVehicleResponse) GetSeats() int32 {
	if x != nil {
		return x.Seats
	}
	return 0
}

func (x *UpdateVehicleResponse) GetChassisNumber() string {
	if x != nil {
		return x.ChassisNumber
	}
	return ""
}

func (x *UpdateVehicleResponse) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *UpdateVehicleResponse) GetEnergy() string {
	if x != nil {
		return x.Energy
	}
	return ""
}

func (x *UpdateVehicleResponse) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *UpdateVehicleResponse) GetWilaya() int32 {
	if x != nil {
		return x.Wilaya
	}
	return 0
}

func (x *UpdateVehicleResponse) GetValeurVenale() float64 {
	if x != nil {
		return x.ValeurVenale
	}
	return 0
}

func (x *UpdateVehicleResponse) GetPaiementCcp() bool {
	if x != nil {
		return x.PaiementCcp
	}
	return false
}

func (x *UpdateVehicleResponse) GetMoins_25Ans() bool {
	if x != nil {
		return x.Moins_25Ans
	}
	return false
}

func (x *UpdateVehicleResponse) GetPermisPlus_1An() bool {
	if x != nil {
		return x.PermisPlus_1An
	}
	return false
}

func (x *UpdateVehicleResponse) GetCarteGrisePath() string {
	if x != nil {
		return x.CarteGrisePath
	}
	return ""
}

type DeleteVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleRequest) Reset() {
	*x = DeleteVehicleRequest{}
	mi := &file_proto_vehicle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleRequest) ProtoMessage() {}

func (x *DeleteVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleRequest.ProtoReflect.Descriptor instead.
func (*DeleteVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVehicleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleResponse) Reset() {
	*x = DeleteVehicleResponse{}
	mi := &file_proto_vehicle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleResponse) ProtoMessage() {}

func (x *DeleteVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleResponse.ProtoReflect.Descriptor instead.
func (*DeleteVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_proto_rawDescGZIP(), []int{8}
}

var File_proto_vehicle_proto protoreflect.FileDescriptor

const file_proto_vehicle_proto_rawDesc = "" +
	"\n" +
	"\x13proto/vehicle.proto\x12\avehicle\"\x88\x04\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12!\n" +
	"\fengine_power\x18\x06 \x01(\tR\venginePower\x12\x14\n" +
	"\x05seats\x18\a \x01(\x05R\x05seats\x12%\n" +
	"\x0echassis_number\x18\b \x01(\tR\rchassisNumber\x12#\n" +
	"\rlicense_plate\x18\t \x01(\tR\flicensePlate\x12\x16\n" +
	"\x06energy\x18\n" +
	" \x01(\tR\x06energy\x12!\n" +
	"\fvehicle_type\x18\v \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06wilaya\x18\f \x01(\x05R\x06wilaya\x12#\n" +
	"\rvaleur_venale\x18\r \x01(\x01R\fvaleurVenale\x12!\n" +
	"\fpaiement_ccp\x18\x0e \x01(\bR\vpaiementCcp\x12 \n" +
	"\fmoins_25_ans\x18\x0f \x01(\bR\n" +
	"moins25Ans\x12&\n" +
	"\x0fpermis_plus_1an\x18\x10 \x01(\bR\rpermisPlus1an\x12(\n" +
	"\x10carte_grise_path\x18\x11 \x01(\tR\x0ecarteGrisePath\"\x84\x04\n" +
	"\x14CreateVehicleRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12!\n" +
	"\fengine_power\x18\x05 \x01(\tR\venginePower\x12\x14\n" +
	"\x05seats\x18\x06 \x01(\x05R\x05seats\x12%\n" +
	"\x0echassis_number\x18\a \x01(\tR\rchassisNumber\x12#\n" +
	"\rlicense_plate\x18\b \x01(\tR\flicensePlate\x12\x16\n" +
	"\x06energy\x18\t \x01(\tR\x06energy\x12!\n" +
	"\fvehicle_type\x18\n" +
	" \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06wilaya\x18\v \x01(\x05R\x06wilaya\x12#\n" +
	"\rvaleur_venale\x18\f \x01(\x01R\fvaleurVenale\x12!\n" +
	"\fpaiement_ccp\x18\r \x01(\bR\vpaiementCcp\x12\x1f\n" +
	"\vmoins25_ans\x18\x0e \x01(\bR\n" +
	"moins25Ans\x12&\n" +
	"\x0fpermis_plus1_an\x18\x0f \x01(\bR\rpermisPlus1An\x12(\n" +
	"\x10carte_grise_path\x18\x10 \x01(\tR\x0ecarteGrisePath\"\x96\x04\n" +
	"\x15CreateVehicleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12!\n" +
	"\fengine_power\x18\x06 \x01(\tR\venginePower\x12\x14\n" +
	"\x05seats\x18\a \x01(\x05R\x05seats\x12%\n" +
	"\x0echassis_number\x18\b \x01(\tR\rchassisNumber\x12#\n" +
	"\rlicense_plate\x18\t \x01(\tR\flicensePlate\x12\x16\n" +
	"\x06energy\x18\n" +
	" \x01(\tR\x06energy\x12!\n" +
	"\fvehicle_type\x18\v \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06wilaya\x18\f \x01(\x05R\x06wilaya\x12#\n" +
	"\rvaleur_venale\x18\r \x01(\x01R\fvaleurVenale\x12!\n" +
	"\fpaiement_ccp\x18\x0e \x01(\bR\vpaiementCcp\x12 \n" +
	"\fmoins_25_ans\x18\x0f \x01(\bR\n" +
	"moins25Ans\x12&\n" +
	"\x0fpermis_plus_1an\x18\x10 \x01(\bR\rpermisPlus1an\x12(\n" +
	"\x10carte_grise_path\x18\x11 \x01(\tR\x0ecarteGrisePath\"#\n" +
	"\x11GetVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x93\x04\n" +
	"\x12GetVehicleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12!\n" +
	"\fengine_power\x18\x06 \x01(\tR\venginePower\x12\x14\n" +
	"\x05seats\x18\a \x01(\x05R\x05seats\x12%\n" +
	"\x0echassis_number\x18\b \x01(\tR\rchassisNumber\x12#\n" +
	"\rlicense_plate\x18\t \x01(\tR\flicensePlate\x12\x16\n" +
	"\x06energy\x18\n" +
	" \x01(\tR\x06energy\x12!\n" +
	"\fvehicle_type\x18\v \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06wilaya\x18\f \x01(\x05R\x06wilaya\x12#\n" +
	"\rvaleur_venale\x18\r \x01(\x01R\fvaleurVenale\x12!\n" +
	"\fpaiement_ccp\x18\x0e \x01(\bR\vpaiementCcp\x12 \n" +
	"\fmoins_25_ans\x18\x0f \x01(\bR\n" +
	"moins25Ans\x12&\n" +
	"\x0fpermis_plus_1an\x18\x10 \x01(\bR\rpermisPlus1an\x12(\n" +
	"\x10carte_grise_path\x18\x11 \x01(\tR\x0ecarteGrisePath\"\x95\x04\n" +
	"\x14UpdateVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12!\n" +
	"\fengine_power\x18\x06 \x01(\tR\venginePower\x12\x14\n" +
	"\x05seats\x18\a \x01(\x05R\x05seats\x12%\n" +
	"\x0echassis_number\x18\b \x01(\tR\rchassisNumber\x12#\n" +
	"\rlicense_plate\x18\t \x01(\tR\flicensePlate\x12\x16\n" +
	"\x06energy\x18\n" +
	" \x01(\tR\x06energy\x12!\n" +
	"\fvehicle_type\x18\v \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06wilaya\x18\f \x01(\x05R\x06wilaya\x12#\n" +
	"\rvaleur_venale\x18\r \x01(\x01R\fvaleurVenale\x12!\n" +
	"\fpaiement_ccp\x18\x0e \x01(\bR\vpaiementCcp\x12 \n" +
	"\fmoins_25_ans\x18\x0f \x01(\bR\n" +
	"moins25Ans\x12&\n" +
	"\x0fpermis_plus_1an\x18\x10 \x01(\bR\rpermisPlus1an\x12(\n" +
	"\x10carte_grise_path\x18\x11 \x01(\tR\x0ecarteGrisePath\"\x96\x04\n" +
	"\x15UpdateVehicleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12!\n" +
	"\fengine_power\x18\x06 \x01(\tR\venginePower\x12\x14\n" +
	"\x05seats\x18\a \x01(\x05R\x05seats\x12%\n" +
	"\x0echassis_number\x18\b \x01(\tR\rchassisNumber\x12#\n" +
	"\rlicense_plate\x18\t \x01(\tR\flicensePlate\x12\x16\n" +
	"\x06energy\x18\n" +
	" \x01(\tR\x06energy\x12!\n" +
	"\fvehicle_type\x18\v \x01(\tR\vvehicleType\x12\x16\n" +
	"\x06wilaya\x18\f \x01(\x05R\x06wilaya\x12#\n" +
	"\rvaleur_venale\x18\r \x01(\x01R\fvaleurVenale\x12!\n" +
	"\fpaiement_ccp\x18\x0e \x01(\bR\vpaiementCcp\x12 \n" +
	"\fmoins_25_ans\x18\x0f \x01(\bR\n" +
	"moins25Ans\x12&\n" +
	"\x0fpermis_plus_1an\x18\x10 \x01(\bR\rpermisPlus1an\x12(\n" +
	"\x10carte_grise_path\x18\x11 \x01(\tR\x0ecarteGrisePath\"&\n" +
	"\x14DeleteVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x17\n" +
	"\x15DeleteVehicleResponse2\xc7\x02\n" +
	"\x0eVehicleService\x12N\n" +
	"\rCreateVehicle\x12\x1d.vehicle.CreateVehicleRequest\x1a\x1e.vehicle.CreateVehicleResponse\x12E\n" +
	"\n" +
	"GetVehicle\x12\x1a.vehicle.GetVehicleRequest\x1a\x1b.vehicle.GetVehicleResponse\x12N\n" +
	"\rUpdateVehicle\x12\x1d.vehicle.UpdateVehicleRequest\x1a\x1e.vehicle.UpdateVehicleResponse\x12N\n" +
	"\rDeleteVehicle\x12\x1d.vehicle.DeleteVehicleRequest\x1a\x1e.vehicle.DeleteVehicleResponseB\x16Z\x14/rpc/vehicle;vehicleb\x06proto3"

var (
	file_proto_vehicle_proto_rawDescOnce sync.Once
	file_proto_vehicle_proto_rawDescData []byte
)

func file_proto_vehicle_proto_rawDescGZIP() []byte {
	file_proto_vehicle_proto_rawDescOnce.Do(func() {
		file_proto_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vehicle_proto_rawDesc), len(file_proto_vehicle_proto_rawDesc)))
	})
	return file_proto_vehicle_proto_rawDescData
}

var file_proto_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_vehicle_proto_goTypes = []any{
	(*Vehicle)(nil),               // 0: vehicle.Vehicle
	(*CreateVehicleRequest)(nil),  // 1: vehicle.CreateVehicleRequest
	(*CreateVehicleResponse)(nil), // 2: vehicle.CreateVehicleResponse
	(*GetVehicleRequest)(nil),     // 3: vehicle.GetVehicleRequest
	(*GetVehicleResponse)(nil),    // 4: vehicle.GetVehicleResponse
	(*UpdateVehicleRequest)(nil),  // 5: vehicle.UpdateVehicleRequest
	(*UpdateVehicleResponse)(nil), // 6: vehicle.UpdateVehicleResponse
	(*DeleteVehicleRequest)(nil),  // 7: vehicle.DeleteVehicleRequest
	(*DeleteVehicleResponse)(nil), // 8: vehicle.DeleteVehicleResponse
}
var file_proto_vehicle_proto_depIdxs = []int32{
	1, // 0: vehicle.VehicleService.CreateVehicle:input_type -> vehicle.CreateVehicleRequest
	3, // 1: vehicle.VehicleService.GetVehicle:input_type -> vehicle.GetVehicleRequest
	5, // 2: vehicle.VehicleService.UpdateVehicle:input_type -> vehicle.UpdateVehicleRequest
	7, // 3: vehicle.VehicleService.DeleteVehicle:input_type -> vehicle.DeleteVehicleRequest
	2, // 4: vehicle.VehicleService.CreateVehicle:output_type -> vehicle.CreateVehicleResponse
	4, // 5: vehicle.VehicleService.GetVehicle:output_type -> vehicle.GetVehicleResponse
	6, // 6: vehicle.VehicleService.UpdateVehicle:output_type -> vehicle.UpdateVehicleResponse
	8, // 7: vehicle.VehicleService.DeleteVehicle:output_type -> vehicle.DeleteVehicleResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_vehicle_proto_init() }
func file_proto_vehicle_proto_init() {
	if File_proto_vehicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vehicle_proto_rawDesc), len(file_proto_vehicle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vehicle_proto_goTypes,
		DependencyIndexes: file_proto_vehicle_proto_depIdxs,
		MessageInfos:      file_proto_vehicle_proto_msgTypes,
	}.Build()
	File_proto_vehicle_proto = out.File
	file_proto_vehicle_proto_goTypes = nil
	file_proto_vehicle_proto_depIdxs = nil
}
