// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/Insurance.proto

package insurance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Insurance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleId     int64                  `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Assuree       bool                   `protobuf:"varint,3,opt,name=assuree,proto3" json:"assuree,omitempty"`
	AssureNom     string                 `protobuf:"bytes,4,opt,name=assure_nom,json=assureNom,proto3" json:"assure_nom,omitempty"`
	AssurePrenom  string                 `protobuf:"bytes,5,opt,name=assure_prenom,json=assurePrenom,proto3" json:"assure_prenom,omitempty"`
	AssureAdresse string                 `protobuf:"bytes,6,opt,name=assure_adresse,json=assureAdresse,proto3" json:"assure_adresse,omitempty"`
	Company       string                 `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	PolicyNumber  string                 `protobuf:"bytes,8,opt,name=policy_number,json=policyNumber,proto3" json:"policy_number,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	AgencyCode    string                 `protobuf:"bytes,11,opt,name=agency_code,json=agencyCode,proto3" json:"agency_code,omitempty"`
	CoverageType  string                 `protobuf:"bytes,12,opt,name=coverage_type,json=coverageType,proto3" json:"coverage_type,omitempty"`
	AssurancePath string                 `protobuf:"bytes,13,opt,name=assurance_path,json=assurancePath,proto3" json:"assurance_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Insurance) Reset() {
	*x = Insurance{}
	mi := &file_proto_Insurance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insurance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insurance) ProtoMessage() {}

func (x *Insurance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Insurance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insurance.ProtoReflect.Descriptor instead.
func (*Insurance) Descriptor() ([]byte, []int) {
	return file_proto_Insurance_proto_rawDescGZIP(), []int{0}
}

func (x *Insurance) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Insurance) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Insurance) GetAssuree() bool {
	if x != nil {
		return x.Assuree
	}
	return false
}

func (x *Insurance) GetAssureNom() string {
	if x != nil {
		return x.AssureNom
	}
	return ""
}

func (x *Insurance) GetAssurePrenom() string {
	if x != nil {
		return x.AssurePrenom
	}
	return ""
}

func (x *Insurance) GetAssureAdresse() string {
	if x != nil {
		return x.AssureAdresse
	}
	return ""
}

func (x *Insurance) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Insurance) GetPolicyNumber() string {
	if x != nil {
		return x.PolicyNumber
	}
	return ""
}

func (x *Insurance) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *Insurance) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *Insurance) GetAgencyCode() string {
	if x != nil {
		return x.AgencyCode
	}
	return ""
}

func (x *Insurance) GetCoverageType() string {
	if x != nil {
		return x.CoverageType
	}
	return ""
}

func (x *Insurance) GetAssurancePath() string {
	if x != nil {
		return x.AssurancePath
	}
	return ""
}

type CreateInsuranceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     int64                  `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Assuree       bool                   `protobuf:"varint,2,opt,name=assuree,proto3" json:"assuree,omitempty"`
	AssureNom     string                 `protobuf:"bytes,3,opt,name=assure_nom,json=assureNom,proto3" json:"assure_nom,omitempty"`
	AssurePrenom  string                 `protobuf:"bytes,4,opt,name=assure_prenom,json=assurePrenom,proto3" json:"assure_prenom,omitempty"`
	AssureAdresse string                 `protobuf:"bytes,5,opt,name=assure_adresse,json=assureAdresse,proto3" json:"assure_adresse,omitempty"`
	Company       string                 `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	PolicyNumber  string                 `protobuf:"bytes,7,opt,name=policy_number,json=policyNumber,proto3" json:"policy_number,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	AgencyCode    string                 `protobuf:"bytes,10,opt,name=agency_code,json=agencyCode,proto3" json:"agency_code,omitempty"`
	CoverageType  string                 `protobuf:"bytes,11,opt,name=coverage_type,json=coverageType,proto3" json:"coverage_type,omitempty"`
	AssurancePath string                 `protobuf:"bytes,12,opt,name=assurance_path,json=assurancePath,proto3" json:"assurance_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInsuranceRequest) Reset() {
	*x = CreateInsuranceRequest{}
	mi := &file_proto_Insurance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInsuranceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInsuranceRequest) ProtoMessage() {}

func (x *CreateInsuranceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Insurance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInsuranceRequest.ProtoReflect.Descriptor instead.
func (*CreateInsuranceRequest) Descriptor() ([]byte, []int) {
	return file_proto_Insurance_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInsuranceRequest) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *CreateInsuranceRequest) GetAssuree() bool {
	if x != nil {
		return x.Assuree
	}
	return false
}

func (x *CreateInsuranceRequest) GetAssureNom() string {
	if x != nil {
		return x.AssureNom
	}
	return ""
}

func (x *CreateInsuranceRequest) GetAssurePrenom() string {
	if x != nil {
		return x.AssurePrenom
	}
	return ""
}

func (x *CreateInsuranceRequest) GetAssureAdresse() string {
	if x != nil {
		return x.AssureAdresse
	}
	return ""
}

func (x *CreateInsuranceRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreateInsuranceRequest) GetPolicyNumber() string {
	if x != nil {
		return x.PolicyNumber
	}
	return ""
}

func (x *CreateInsuranceRequest) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *CreateInsuranceRequest) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *CreateInsuranceRequest) GetAgencyCode() string {
	if x != nil {
		return x.AgencyCode
	}
	return ""
}

func (x *CreateInsuranceRequest) GetCoverageType() string {
	if x != nil {
		return x.CoverageType
	}
	return ""
}

func (x *CreateInsuranceRequest) GetAssurancePath() string {
	if x != nil {
		return x.AssurancePath
	}
	return ""
}

type CreateInsuranceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleId     int64                  `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Assuree       bool                   `protobuf:"varint,3,opt,name=assuree,proto3" json:"assuree,omitempty"`
	AssureNom     string                 `protobuf:"bytes,4,opt,name=assure_nom,json=assureNom,proto3" json:"assure_nom,omitempty"`
	AssurePrenom  string                 `protobuf:"bytes,5,opt,name=assure_prenom,json=assurePrenom,proto3" json:"assure_prenom,omitempty"`
	AssureAdresse string                 `protobuf:"bytes,6,opt,name=assure_adresse,json=assureAdresse,proto3" json:"assure_adresse,omitempty"`
	Company       string                 `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	PolicyNumber  string                 `protobuf:"bytes,8,opt,name=policy_number,json=policyNumber,proto3" json:"policy_number,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	AgencyCode    string                 `protobuf:"bytes,11,opt,name=agency_code,json=agencyCode,proto3" json:"agency_code,omitempty"`
	CoverageType  string                 `protobuf:"bytes,12,opt,name=coverage_type,json=coverageType,proto3" json:"coverage_type,omitempty"`
	AssurancePath string                 `protobuf:"bytes,13,opt,name=assurance_path,json=assurancePath,proto3" json:"assurance_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInsuranceResponse) Reset() {
	*x = CreateInsuranceResponse{}
	mi := &file_proto_Insurance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInsuranceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInsuranceResponse) ProtoMessage() {}

func (x *CreateInsuranceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Insurance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInsuranceResponse.ProtoReflect.Descriptor instead.
func (*CreateInsuranceResponse) Descriptor() ([]byte, []int) {
	return file_proto_Insurance_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInsuranceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateInsuranceResponse) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *CreateInsuranceResponse) GetAssuree() bool {
	if x != nil {
		return x.Assuree
	}
	return false
}

func (x *CreateInsuranceResponse) GetAssureNom() string {
	if x != nil {
		return x.AssureNom
	}
	return ""
}

func (x *CreateInsuranceResponse) GetAssurePrenom() string {
	if x != nil {
		return x.AssurePrenom
	}
	return ""
}

func (x *CreateInsuranceResponse) GetAssureAdresse() string {
	if x != nil {
		return x.AssureAdresse
	}
	return ""
}

func (x *CreateInsuranceResponse) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreateInsuranceResponse) GetPolicyNumber() string {
	if x != nil {
		return x.PolicyNumber
	}
	return ""
}

func (x *CreateInsuranceResponse) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *CreateInsuranceResponse) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *CreateInsuranceResponse) GetAgencyCode() string {
	if x != nil {
		return x.AgencyCode
	}
	return ""
}

func (x *CreateInsuranceResponse) GetCoverageType() string {
	if x != nil {
		return x.CoverageType
	}
	return ""
}

func (x *CreateInsuranceResponse) GetAssurancePath() string {
	if x != nil {
		return x.AssurancePath
	}
	return ""
}

type GetInsuranceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInsuranceRequest) Reset() {
	*x = GetInsuranceRequest{}
	mi := &file_proto_Insurance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInsuranceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInsuranceRequest) ProtoMessage() {}

func (x *GetInsuranceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Insurance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInsuranceRequest.ProtoReflect.Descriptor instead.
func (*GetInsuranceRequest) Descriptor() ([]byte, []int) {
	return file_proto_Insurance_proto_rawDescGZIP(), []int{3}
}

func (x *GetInsuranceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetInsuranceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleId     int64                  `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Assuree       bool                   `protobuf:"varint,3,opt,name=assuree,proto3" json:"assuree,omitempty"`
	AssureNom     string                 `protobuf:"bytes,4,opt,name=assure_nom,json=assureNom,proto3" json:"assure_nom,omitempty"`
	AssurePrenom  string                 `protobuf:"bytes,5,opt,name=assure_prenom,json=assurePrenom,proto3" json:"assure_prenom,omitempty"`
	AssureAdresse string                 `protobuf:"bytes,6,opt,name=assure_adresse,json=assureAdresse,proto3" json:"assure_adresse,omitempty"`
	Company       string                 `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	PolicyNumber  string                 `protobuf:"bytes,8,opt,name=policy_number,json=policyNumber,proto3" json:"policy_number,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	AgencyCode    string                 `protobuf:"bytes,11,opt,name=agency_code,json=agencyCode,proto3" json:"agency_code,omitempty"`
	CoverageType  string                 `protobuf:"bytes,12,opt,name=coverage_type,json=coverageType,proto3" json:"coverage_type,omitempty"`
	AssurancePath string                 `protobuf:"bytes,13,opt,name=assurance_path,json=assurancePath,proto3" json:"assurance_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInsuranceResponse) Reset() {
	*x = GetInsuranceResponse{}
	mi := &file_proto_Insurance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInsuranceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInsuranceResponse) ProtoMessage() {}

func (x *GetInsuranceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Insurance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInsuranceResponse.ProtoReflect.Descriptor instead.
func (*GetInsuranceResponse) Descriptor() ([]byte, []int) {
	return file_proto_Insurance_proto_rawDescGZIP(), []int{4}
}

func (x *GetInsuranceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetInsuranceResponse) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *GetInsuranceResponse) GetAssuree() bool {
	if x != nil {
		return x.Assuree
	}
	return false
}

func (x *GetInsuranceResponse) GetAssureNom() string {
	if x != nil {
		return x.AssureNom
	}
	return ""
}

func (x *GetInsuranceResponse) GetAssurePrenom() string {
	if x != nil {
		return x.AssurePrenom
	}
	return ""
}

func (x *GetInsuranceResponse) GetAssureAdresse() string {
	if x != nil {
		return x.AssureAdresse
	}
	return ""
}

func (x *GetInsuranceResponse) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *GetInsuranceResponse) GetPolicyNumber() string {
	if x != nil {
		return x.PolicyNumber
	}
	return ""
}

func (x *GetInsuranceResponse) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *GetInsuranceResponse) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *GetInsuranceResponse) GetAgencyCode() string {
	if x != nil {
		return x.AgencyCode
	}
	return ""
}

func (x *GetInsuranceResponse) GetCoverageType() string {
	if x != nil {
		return x.CoverageType
	}
	return ""
}

func (x *GetInsuranceResponse) GetAssurancePath() string {
	if x != nil {
		return x.AssurancePath
	}
	return ""
}

type UpdateInsuranceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleId     int64                  `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Assuree       bool                   `protobuf:"varint,3,opt,name=assuree,proto3" json:"assuree,omitempty"`
	AssureNom     string                 `protobuf:"bytes,4,opt,name=assure_nom,json=assureNom,proto3" json:"assure_nom,omitempty"`
	AssurePrenom  string                 `protobuf:"bytes,5,opt,name=assure_prenom,json=assurePrenom,proto3" json:"assure_prenom,omitempty"`
	AssureAdresse string                 `protobuf:"bytes,6,opt,name=assure_adresse,json=assureAdresse,proto3" json:"assure_adresse,omitempty"`
	Company       string                 `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	PolicyNumber  string                 `protobuf:"bytes,8,opt,name=policy_number,json=policyNumber,proto3" json:"policy_number,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	AgencyCode    string                 `protobuf:"bytes,11,opt,name=agency_code,json=agencyCode,proto3" json:"agency_code,omitempty"`
	CoverageType  string                 `protobuf:"bytes,12,opt,name=coverage_type,json=coverageType,proto3" json:"coverage_type,omitempty"`
	AssurancePath string                 `protobuf:"bytes,13,opt,name=assurance_path,json=assurancePath,proto3" json:"assurance_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInsuranceRequest) Reset() {
	*x = UpdateInsuranceRequest{}
	mi := &file_proto_Insurance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInsuranceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInsuranceRequest) ProtoMessage() {}

func (x *UpdateInsuranceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Insurance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInsuranceRequest.ProtoReflect.Descriptor instead.
func (*UpdateInsuranceRequest) Descriptor() ([]byte, []int) {
	return file_proto_Insurance_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateInsuranceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateInsuranceRequest) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *UpdateInsuranceRequest) GetAssuree() bool {
	if x != nil {
		return x.Assuree
	}
	return false
}

func (x *UpdateInsuranceRequest) GetAssureNom() string {
	if x != nil {
		return x.AssureNom
	}
	return ""
}

func (x *UpdateInsuranceRequest) GetAssurePrenom() string {
	if x != nil {
		return x.AssurePrenom
	}
	return ""
}

func (x *UpdateInsuranceRequest) GetAssureAdresse() string {
	if x != nil {
		return x.AssureAdresse
	}
	return ""
}

func (x *UpdateInsuranceRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UpdateInsuranceRequest) GetPolicyNumber() string {
	if x != nil {
		return x.PolicyNumber
	}
	return ""
}

func (x *UpdateInsuranceRequest) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *UpdateInsuranceRequest) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *UpdateInsuranceRequest) GetAgencyCode() string {
	if x != nil {
		return x.AgencyCode
	}
	return ""
}

func (x *UpdateInsuranceRequest) GetCoverageType() string {
	if x != nil {
		return x.CoverageType
	}
	return ""
}

func (x *UpdateInsuranceRequest) GetAssurancePath() string {
	if x != nil {
		return x.AssurancePath
	}
	return ""
}

type UpdateInsuranceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VehicleId     int64                  `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Assuree       bool                   `protobuf:"varint,3,opt,name=assuree,proto3" json:"assuree,omitempty"`
	AssureNom     string                 `protobuf:"bytes,4,opt,name=assure_nom,json=assureNom,proto3" json:"assure_nom,omitempty"`
	AssurePrenom  string                 `protobuf:"bytes,5,opt,name=assure_prenom,json=assurePrenom,proto3" json:"assure_prenom,omitempty"`
	AssureAdresse string                 `protobuf:"bytes,6,opt,name=assure_adresse,json=assureAdresse,proto3" json:"assure_adresse,omitempty"`
	Company       string                 `protobuf:"bytes,7,opt,name=company,proto3" json:"company,omitempty"`
	PolicyNumber  string                 `protobuf:"bytes,8,opt,name=policy_number,json=policyNumber,proto3" json:"policy_number,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	AgencyCode    string                 `protobuf:"bytes,11,opt,name=agency_code,json=agencyCode,proto3" json:"agency_code,omitempty"`
	CoverageType  string                 `protobuf:"bytes,12,opt,name=coverage_type,json=coverageType,proto3" json:"coverage_type,omitempty"`
	AssurancePath string                 `protobuf:"bytes,13,opt,name=assurance_path,json=assurancePath,proto3" json:"assurance_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInsuranceResponse) Reset() {
	*x = UpdateInsuranceResponse{}
	mi := &file_proto_Insurance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInsuranceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInsuranceResponse) ProtoMessage() {}

func (x *UpdateInsuranceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Insurance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInsuranceResponse.ProtoReflect.Descriptor instead.
func (*UpdateInsuranceResponse) Descriptor() ([]byte, []int) {
	return file_proto_Insurance_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateInsuranceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateInsuranceResponse) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *UpdateInsuranceResponse) GetAssuree() bool {
	if x != nil {
		return x.Assuree
	}
	return false
}

func (x *UpdateInsuranceResponse) GetAssureNom() string {
	if x != nil {
		return x.AssureNom
	}
	return ""
}

func (x *UpdateInsuranceResponse) GetAssurePrenom() string {
	if x != nil {
		return x.AssurePrenom
	}
	return ""
}

func (x *UpdateInsuranceResponse) GetAssureAdresse() string {
	if x != nil {
		return x.AssureAdresse
	}
	return ""
}

func (x *UpdateInsuranceResponse) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UpdateInsuranceResponse) GetPolicyNumber() string {
	if x != nil {
		return x.PolicyNumber
	}
	return ""
}

func (x *UpdateInsuranceResponse) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *UpdateInsuranceResponse) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *UpdateInsuranceResponse) GetAgencyCode() string {
	if x != nil {
		return x.AgencyCode
	}
	return ""
}

func (x *UpdateInsuranceResponse) GetCoverageType() string {
	if x != nil {
		return x.CoverageType
	}
	return ""
}

func (x *UpdateInsuranceResponse) GetAssurancePath() string {
	if x != nil {
		return x.AssurancePath
	}
	return ""
}

type DeleteInsuranceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInsuranceRequest) Reset() {
	*x = DeleteInsuranceRequest{}
	mi := &file_proto_Insurance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInsuranceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInsuranceRequest) ProtoMessage() {}

func (x *DeleteInsuranceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Insurance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInsuranceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInsuranceRequest) Descriptor() ([]byte, []int) {
	return file_proto_Insurance_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteInsuranceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteInsuranceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInsuranceResponse) Reset() {
	*x = DeleteInsuranceResponse{}
	mi := &file_proto_Insurance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInsuranceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInsuranceResponse) ProtoMessage() {}

func (x *DeleteInsuranceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Insurance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInsuranceResponse.ProtoReflect.Descriptor instead.
func (*DeleteInsuranceResponse) Descriptor() ([]byte, []int) {
	return file_proto_Insurance_proto_rawDescGZIP(), []int{8}
}

var File_proto_Insurance_proto protoreflect.FileDescriptor

const file_proto_Insurance_proto_rawDesc = "" +
	"\n" +
	"\x15proto/Insurance.proto\x12\tinsurance\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x03\n" +
	"\tInsurance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\x03R\tvehicleId\x12\x18\n" +
	"\aassuree\x18\x03 \x01(\bR\aassuree\x12\x1d\n" +
	"\n" +
	"assure_nom\x18\x04 \x01(\tR\tassureNom\x12#\n" +
	"\rassure_prenom\x18\x05 \x01(\tR\fassurePrenom\x12%\n" +
	"\x0eassure_adresse\x18\x06 \x01(\tR\rassureAdresse\x12\x18\n" +
	"\acompany\x18\a \x01(\tR\acompany\x12#\n" +
	"\rpolicy_number\x18\b \x01(\tR\fpolicyNumber\x129\n" +
	"\n" +
	"valid_from\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x12\x1f\n" +
	"\vagency_code\x18\v \x01(\tR\n" +
	"agencyCode\x12#\n" +
	"\rcoverage_type\x18\f \x01(\tR\fcoverageType\x12%\n" +
	"\x0eassurance_path\x18\r \x01(\tR\rassurancePath\"\xda\x03\n" +
	"\x16CreateInsuranceRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\x03R\tvehicleId\x12\x18\n" +
	"\aassuree\x18\x02 \x01(\bR\aassuree\x12\x1d\n" +
	"\n" +
	"assure_nom\x18\x03 \x01(\tR\tassureNom\x12#\n" +
	"\rassure_prenom\x18\x04 \x01(\tR\fassurePrenom\x12%\n" +
	"\x0eassure_adresse\x18\x05 \x01(\tR\rassureAdresse\x12\x18\n" +
	"\acompany\x18\x06 \x01(\tR\acompany\x12#\n" +
	"\rpolicy_number\x18\a \x01(\tR\fpolicyNumber\x129\n" +
	"\n" +
	"valid_from\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x12\x1f\n" +
	"\vagency_code\x18\n" +
	" \x01(\tR\n" +
	"agencyCode\x12#\n" +
	"\rcoverage_type\x18\v \x01(\tR\fcoverageType\x12%\n" +
	"\x0eassurance_path\x18\f \x01(\tR\rassurancePath\"\xeb\x03\n" +
	"\x17CreateInsuranceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\x03R\tvehicleId\x12\x18\n" +
	"\aassuree\x18\x03 \x01(\bR\aassuree\x12\x1d\n" +
	"\n" +
	"assure_nom\x18\x04 \x01(\tR\tassureNom\x12#\n" +
	"\rassure_prenom\x18\x05 \x01(\tR\fassurePrenom\x12%\n" +
	"\x0eassure_adresse\x18\x06 \x01(\tR\rassureAdresse\x12\x18\n" +
	"\acompany\x18\a \x01(\tR\acompany\x12#\n" +
	"\rpolicy_number\x18\b \x01(\tR\fpolicyNumber\x129\n" +
	"\n" +
	"valid_from\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x12\x1f\n" +
	"\vagency_code\x18\v \x01(\tR\n" +
	"agencyCode\x12#\n" +
	"\rcoverage_type\x18\f \x01(\tR\fcoverageType\x12%\n" +
	"\x0eassurance_path\x18\r \x01(\tR\rassurancePath\"%\n" +
	"\x13GetInsuranceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe8\x03\n" +
	"\x14GetInsuranceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\x03R\tvehicleId\x12\x18\n" +
	"\aassuree\x18\x03 \x01(\bR\aassuree\x12\x1d\n" +
	"\n" +
	"assure_nom\x18\x04 \x01(\tR\tassureNom\x12#\n" +
	"\rassure_prenom\x18\x05 \x01(\tR\fassurePrenom\x12%\n" +
	"\x0eassure_adresse\x18\x06 \x01(\tR\rassureAdresse\x12\x18\n" +
	"\acompany\x18\a \x01(\tR\acompany\x12#\n" +
	"\rpolicy_number\x18\b \x01(\tR\fpolicyNumber\x129\n" +
	"\n" +
	"valid_from\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x12\x1f\n" +
	"\vagency_code\x18\v \x01(\tR\n" +
	"agencyCode\x12#\n" +
	"\rcoverage_type\x18\f \x01(\tR\fcoverageType\x12%\n" +
	"\x0eassurance_path\x18\r \x01(\tR\rassurancePath\"\xea\x03\n" +
	"\x16UpdateInsuranceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\x03R\tvehicleId\x12\x18\n" +
	"\aassuree\x18\x03 \x01(\bR\aassuree\x12\x1d\n" +
	"\n" +
	"assure_nom\x18\x04 \x01(\tR\tassureNom\x12#\n" +
	"\rassure_prenom\x18\x05 \x01(\tR\fassurePrenom\x12%\n" +
	"\x0eassure_adresse\x18\x06 \x01(\tR\rassureAdresse\x12\x18\n" +
	"\acompany\x18\a \x01(\tR\acompany\x12#\n" +
	"\rpolicy_number\x18\b \x01(\tR\fpolicyNumber\x129\n" +
	"\n" +
	"valid_from\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x12\x1f\n" +
	"\vagency_code\x18\v \x01(\tR\n" +
	"agencyCode\x12#\n" +
	"\rcoverage_type\x18\f \x01(\tR\fcoverageType\x12%\n" +
	"\x0eassurance_path\x18\r \x01(\tR\rassurancePath\"\xeb\x03\n" +
	"\x17UpdateInsuranceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\x03R\tvehicleId\x12\x18\n" +
	"\aassuree\x18\x03 \x01(\bR\aassuree\x12\x1d\n" +
	"\n" +
	"assure_nom\x18\x04 \x01(\tR\tassureNom\x12#\n" +
	"\rassure_prenom\x18\x05 \x01(\tR\fassurePrenom\x12%\n" +
	"\x0eassure_adresse\x18\x06 \x01(\tR\rassureAdresse\x12\x18\n" +
	"\acompany\x18\a \x01(\tR\acompany\x12#\n" +
	"\rpolicy_number\x18\b \x01(\tR\fpolicyNumber\x129\n" +
	"\n" +
	"valid_from\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x12\x1f\n" +
	"\vagency_code\x18\v \x01(\tR\n" +
	"agencyCode\x12#\n" +
	"\rcoverage_type\x18\f \x01(\tR\fcoverageType\x12%\n" +
	"\x0eassurance_path\x18\r \x01(\tR\rassurancePath\"(\n" +
	"\x16DeleteInsuranceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x19\n" +
	"\x17DeleteInsuranceResponse2\xf1\x02\n" +
	"\x10InsuranceService\x12X\n" +
	"\x0fCreateInsurance\x12!.insurance.CreateInsuranceRequest\x1a\".insurance.CreateInsuranceResponse\x12O\n" +
	"\fGetInsurance\x12\x1e.insurance.GetInsuranceRequest\x1a\x1f.insurance.GetInsuranceResponse\x12X\n" +
	"\x0fUpdateInsurance\x12!.insurance.UpdateInsuranceRequest\x1a\".insurance.UpdateInsuranceResponse\x12X\n" +
	"\x0fDeleteInsurance\x12!.insurance.DeleteInsuranceRequest\x1a\".insurance.DeleteInsuranceResponseB\x1aZ\x18/rpc/insurance;insuranceb\x06proto3"

var (
	file_proto_Insurance_proto_rawDescOnce sync.Once
	file_proto_Insurance_proto_rawDescData []byte
)

func file_proto_Insurance_proto_rawDescGZIP() []byte {
	file_proto_Insurance_proto_rawDescOnce.Do(func() {
		file_proto_Insurance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_Insurance_proto_rawDesc), len(file_proto_Insurance_proto_rawDesc)))
	})
	return file_proto_Insurance_proto_rawDescData
}

var file_proto_Insurance_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_Insurance_proto_goTypes = []any{
	(*Insurance)(nil),               // 0: insurance.Insurance
	(*CreateInsuranceRequest)(nil),  // 1: insurance.CreateInsuranceRequest
	(*CreateInsuranceResponse)(nil), // 2: insurance.CreateInsuranceResponse
	(*GetInsuranceRequest)(nil),     // 3: insurance.GetInsuranceRequest
	(*GetInsuranceResponse)(nil),    // 4: insurance.GetInsuranceResponse
	(*UpdateInsuranceRequest)(nil),  // 5: insurance.UpdateInsuranceRequest
	(*UpdateInsuranceResponse)(nil), // 6: insurance.UpdateInsuranceResponse
	(*DeleteInsuranceRequest)(nil),  // 7: insurance.DeleteInsuranceRequest
	(*DeleteInsuranceResponse)(nil), // 8: insurance.DeleteInsuranceResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_proto_Insurance_proto_depIdxs = []int32{
	9,  // 0: insurance.Insurance.valid_from:type_name -> google.protobuf.Timestamp
	9,  // 1: insurance.Insurance.valid_to:type_name -> google.protobuf.Timestamp
	9,  // 2: insurance.CreateInsuranceRequest.valid_from:type_name -> google.protobuf.Timestamp
	9,  // 3: insurance.CreateInsuranceRequest.valid_to:type_name -> google.protobuf.Timestamp
	9,  // 4: insurance.CreateInsuranceResponse.valid_from:type_name -> google.protobuf.Timestamp
	9,  // 5: insurance.CreateInsuranceResponse.valid_to:type_name -> google.protobuf.Timestamp
	9,  // 6: insurance.GetInsuranceResponse.valid_from:type_name -> google.protobuf.Timestamp
	9,  // 7: insurance.GetInsuranceResponse.valid_to:type_name -> google.protobuf.Timestamp
	9,  // 8: insurance.UpdateInsuranceRequest.valid_from:type_name -> google.protobuf.Timestamp
	9,  // 9: insurance.UpdateInsuranceRequest.valid_to:type_name -> google.protobuf.Timestamp
	9,  // 10: insurance.UpdateInsuranceResponse.valid_from:type_name -> google.protobuf.Timestamp
	9,  // 11: insurance.UpdateInsuranceResponse.valid_to:type_name -> google.protobuf.Timestamp
	1,  // 12: insurance.InsuranceService.CreateInsurance:input_type -> insurance.CreateInsuranceRequest
	3,  // 13: insurance.InsuranceService.GetInsurance:input_type -> insurance.GetInsuranceRequest
	5,  // 14: insurance.InsuranceService.UpdateInsurance:input_type -> insurance.UpdateInsuranceRequest
	7,  // 15: insurance.InsuranceService.DeleteInsurance:input_type -> insurance.DeleteInsuranceRequest
	2,  // 16: insurance.InsuranceService.CreateInsurance:output_type -> insurance.CreateInsuranceResponse
	4,  // 17: insurance.InsuranceService.GetInsurance:output_type -> insurance.GetInsuranceResponse
	6,  // 18: insurance.InsuranceService.UpdateInsurance:output_type -> insurance.UpdateInsuranceResponse
	8,  // 19: insurance.InsuranceService.DeleteInsurance:output_type -> insurance.DeleteInsuranceResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_Insurance_proto_init() }
func file_proto_Insurance_proto_init() {
	if File_proto_Insurance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_Insurance_proto_rawDesc), len(file_proto_Insurance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Insurance_proto_goTypes,
		DependencyIndexes: file_proto_Insurance_proto_depIdxs,
		MessageInfos:      file_proto_Insurance_proto_msgTypes,
	}.Build()
	File_proto_Insurance_proto = out.File
	file_proto_Insurance_proto_goTypes = nil
	file_proto_Insurance_proto_depIdxs = nil
}
